@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


class DecisionTreeWidget <<Component>> {
        - treeCanvas:TreeCanvas
        + DecisionTreeWidget(nodes : LayoutNodeDTO[], edges : EdgeDTO[], activePath : String[])
}
!include TreeCanvas.puml
 
DecisionTreeWidget *-- TreeCanvas

@enduml