@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

!include src/PB/DocumentazioneEsterna/Specifica_Tecnica/content/05-diagrammi-classi/uml/puml/Frontend/decision-tree/components/StateConfig.puml



class EvaluationBadge{
        -store:DecisionTreeSore
        -{static}stateConfig:map<String,StateConfig>

        + EvaluationBadge()
}
@enduml