@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class StateConfig{
        +label:String
        +icon:String
        +cssClass:String
}

@enduml