@startuml GetRequirementEvaluationDetailService
skinparam classAttributeIconSize 0

class GetRequirementEvaluationDetailService <<Application Service>> {
    + get_evaluation_detail(command: GetRequirementCommand): RequirementEvaluationDetail
}

@enduml