@startuml CreateDeviceCommand
skinparam classAttributeIconSize 0

class CreateDeviceCommand {
    + device_name: String
    + device_os: String
    + device_description: String
    + standard_id: String
}
@enduml