@startuml UpdateAssetCommand
skinparam classAttributeIconSize 0


class UpdateAssetCommand {
    + device_id: String
    + asset_id: String
    + name: String
    + asset_type: AssetType
    + description: String
    + session_id: String
}

@enduml