
#include "01-dominio/_index.typ"
#include "02-area_device/_index.typ"
#include "03-area_asset/_index.typ"
#include "04-import/_index.typ"
#include "05-export/_index.typ"
#include "06-sessione/_index.typ"
#include "07-area_navigazione/_index.typ"
#include "08-generazione_report/_index.typ"
#include "09-frontend/_index.typ"