@startuml Modello_di_Dominio
skinparam linetype ortho
skinparam packageStyle rectangle

package "1. Evaluation Object" {
    !include Device.puml
    !include AssetAnagraphic.puml
    !include AssetType.puml
    !include Asset.puml
    !include AssetProprieties.puml
    !include AssetEvidence.puml
}

package "2. Compliance Standard" {
    !include ComplianceStandard.puml
    !include DecisionNode.puml
    !include Node.puml
    !include LeafNode.puml
    !include DecisionTree.puml
    !include Requirement.puml
    !include StandardVerdict.puml
}

package "3. Evaluation Engine" {
    !include EvaluationEngine.puml
    !include EvaluationState.puml
    
}

package "4. Evaluation Output" {
    !include DeviceEvaluationResult.puml
    !include AssetEvaluationResult.puml
    !include RequirementEvaluationResult.puml

    !include DeviceEvaluationDetail.puml
    !include AssetEvaluationDetail.puml
    !include RequirementEvaluationDetail.puml
    !include NodeDetail.puml
}

package "5. Session" {
    !include SessionHandler.puml
    !include EvaluationSession.puml
}

package "6. Utils" {
    !include ExportedFile.puml
    !include DeviceSummary.puml
}


EvaluationEngine --> DeviceEvaluationResult

"5. Session" -[hidden]down- "6. Utils"


@enduml