@startuml Asset
skinparam classAttributeIconSize 0
class Asset {
    + id: String
    + anagraphic: AssetAnagraphic
    + proprieties: AssetProperties

    + set_node_choice(requirement_id: String, node_id: String, value: Bool): void
    + set_justification(requirement_id: String, justification: String): void
    + update_anagraphic(name: String, asset_type: AssetType, description: String): Asset
    + get_evidence(requirement_id: String): AssetEvidence
}

Asset *-- "1" AssetAnagraphic
Asset *-- "1" AssetProperties

@enduml