@startuml ComplianceStandard
skinparam linetype ortho
skinparam classAttributeIconSize 0

class ComplianceStandard {
    - standard_id: String
    - name: String
    - version_number: String
    - requirements: List<Requirement>

    + get_requirement(requirement_id: String): Requirement
    + evaluate_requirement(requirement_id: String, answers: AssetEvidence): EvaluationState
}
ComplianceStandard *-- "1..*" Requirement

@enduml