@startuml Requirement
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Requirement {
    - requirement_id: String
    - name: String
    - description: String
    - target_description: String
    - dependency_ids: List<String>
    - decision_tree: DecisionTree

    + evaluate(answer: AssetEvidence, dependency_states: List<List<String, EvaluationState>>): EvaluationState
}

Requirement *-- "0..1" DecisionTree

@enduml