

@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


!include ../store/DecisionTreeStore.puml
!include ../api/EvaluationAPIClient.puml
!include ../engine/EvaluationEngine.puml
!include ../layout/D3LayoutEngine.puml
!include ../layout/LayoutResult.puml
!include ../models/NodeDTO.puml

DecisionTreeStore --> EvaluationAPIClient
DecisionTreeStore --> EvaluationEngine
DecisionTreeStore ..> D3LayoutEngine
DecisionTreeStore .l.> LayoutResult
DecisionTreeStore .l.> NodeDTO


@enduml