@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml



!include ../components/EvaluationBadge.puml
!include ../components/StateConfig.puml

EvaluationBadge --> StateConfig
@enduml