

@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


!include ../layout/D3LayoutEngine.puml
!include ../layout/LayoutConfig.puml
!include ../layout/LayoutResult.puml
!include ../layout/HierarchyNode.puml
!include ../layout/LayotNodeDTO.puml
!include ../layout/EdgeDTO.puml


D3LayoutEngine --> LayoutConfig
D3LayoutEngine ..> HierarchyNode
D3LayoutEngine ..> LayoutNodeDTO
D3LayoutEngine ..> EdgeDTO
D3LayoutEngine ..> LayoutResult

@enduml