

@startuml
skinparam linetype ortho
skinparam nodesep 0
skinparam ranksep 80
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


!include ../RequirementEvaluationWidget.puml
!include ../store/DecisionTreeStore.puml
 class TreeSidebar
 class EvaluationBadge
 class JustificationForm
 class RequirementEvaluationWidget







RequirementEvaluationWidget -l->DecisionTreeStore
RequirementEvaluationWidget *-- DecisionTreeWidget

RequirementEvaluationWidget *-- EvaluationBadge
RequirementEvaluationWidget *-- JustificationForm

RequirementEvaluationWidget *-- TreeSidebar


@enduml