@startuml classe_asset
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0


package "Inbound Adapter" {
 class AssetController <<Flask Blueprint>> {
   +getListaAsset(device_id: String, req: Request): Response
   +creaAsset(device_id: String, req: Request): Response
   +getDettaglioAsset(device_id: String, asset_id: String): Response
   +modificaAsset(device_id: String, asset_id: String, req: Request): Response
   +eliminaAsset(device_id: String, asset_id: String): Response
 }
}


package "Outbound Adapter" {
 class MongoAssetAdapter <<Mongo Repository>> {
   -collection: pymongo.Collection
   +save(device_id: String, a: Asset): void
   +findById(device_id: String, asset_id: String): Asset
   +findAllByDevice(device_id: String): List<Asset>
   +deleteById(device_id: String, asset_id: String): void
 }
}


package "Ports" {
 interface InterfaceAssetUseCase <<Inbound Port>> {
   +getListaAsset(device_id: String): List<Asset>
   +creaAsset(device_id: String, dto: CreaAssetDTO): Asset
   +getDettaglioAsset(device_id: String, asset_id: String): Asset
   +modificaAsset(device_id: String, asset_id: String, dto: ModificaAssetDTO): Asset
   +eliminaAsset(device_id: String, asset_id: String): void
 }


 interface InterfaceAssetRepository <<Outbound Port>> {
   +save(device_id: String, a: Asset): void
   +findById(device_id: String, asset_id: String): Asset
   +findAllByDevice(device_id: String): List<Asset>
   +deleteById(device_id: String, asset_id: String): void
 }
}


package "Application Core" {
 class AssetService <<Application Service>> {
   -repository: InterfaceAssetRepository
   +getListaAsset(device_id: String): List<Asset>
   +creaAsset(device_id: String, dto: CreaAssetDTO): Asset
   +getDettaglioAsset(device_id: String, asset_id: String): Asset
   +modificaAsset(device_id: String, asset_id: String, dto: ModificaAssetDTO): Asset
   +eliminaAsset(device_id: String, asset_id: String): void
   -validaRegoleBusiness(a: Asset): void
 }


 class Asset <<Entity>> {
   -id: String
   -nome: String
   -descrizione: String
   -tipo: TipoAsset
   -lista_valutazioni: List<ValutazioneRequisito>
   +aggiungiValutazione(v: ValutazioneRequisito): void
   +getValutazioneByRequisito(codice: String): ValutazioneRequisito
 }


 enum TipoAsset {
   SECURITY
   NETWORK
 }
}


AssetController ..> InterfaceAssetUseCase : utilizza
InterfaceAssetUseCase <|.. AssetService : implementa
AssetService ..> InterfaceAssetRepository : utilizza
InterfaceAssetRepository <|.. MongoAssetAdapter : implementa
AssetService --> Asset : crea e modifica
Asset --> TipoAsset : usa


@enduml
