@startuml classe_valutazione
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam Linetype ortho

package "Inbound Adapter" <<Rectangle>> {
  class FlaskValutazioneRequestHandler <<Flask Blueprint>> {
    - valutazione_port: ValutazionePort
    + __init__(valutazione_port: ValutazionePort)
    + answer_node(session_id: string): Response
    + add_justification(session_id: string): Response
    + get_status(session_id: string): Response
    + get_assessment_state(asset_id:string,requirement_id:string) : Response
  
  
  }
  class Request <<Flask>> {
  }

  note right of Request
    Oggetto globale di Flask.
    Accessibile tramite import
    nei metodi dei request handler
    per estrarre i dati della
    richiesta HTTP corrente.
  end note
}

package "business logic"{

package "Application Services" <<Rectangle>>  {

    class ValutazioneService <<Application Service>> {
      - session_cache: SessionCachePort
      + __init__(session_cache: SessionCachePort)
      + answer_node(session_id: string, dto: AnswerNodeDTO): void
      + add_justification(session_id: string, dto: JustificationDTO): void
      + get_valutazione_status(session_id: string): ValutazioneStatusDTO
      + get_assessment_state(asset_id:string,requirement_id:string) : StatoValutazione | null
    
    }
}
package "Inbound Ports" <<Rectangle>> {
    interface ValutazionePort <<interface>> {
      + answer_node(session_id: string, dto: AnswerNodeDTO): void
      + add_justification(session_id: string, dto: JustificationDTO): void
      + get_valutazione_status(session_id: string): ValutazioneStatusDTO
      + get_assessment_state(asset_id:string,requirement_id:string) : StatoValutazione | null
  
  }

}

package "Outbound Ports" <<Rectangle>> {
    interface SessionCachePort <<interface>> {
      + save_session(session: Session): void
      + get_session(session_id: string): Session
      + delete_session(session_id: string): void
      + has_active_session(): bool
    }


}

package "Domain" <<Rectangle>> {
    class Report {
      - device: Device
      - model: Model
      + answer_node(node_code: string, answer: bool): void
      + add_justification(asset_id: string, requirement_code: string, text: string): void
      + get_all_assets(): list[Asset]
      + get_assessment_state(asset_id:string,requirement_id:string) : StatoValutazione | null
    }

    class Device <<Aggregate Root>> {
    }

    class Model {
    }


    class Session {
      - session_id: string
      - session_type: SessionType
      - report: Report
      + get_report(): Report
    }


  enum StatoValutazione {
    IN_CORSO
    PASS
    FAIL
    NA
  }


}
}
package "Outbound Adapter" {
  class InMemorySessionCache {
    - sessions: dictionary[string:Session]
    + save_session(session: Session): void
    + get_session(session_id: string): Session
    + delete_session(session_id: string): void
    + has_active_session(): bool
  }
}



' --- Relazioni ---

' Inbound Adapter -> Ports
FlaskValutazioneRequestHandler --> ValutazionePort : " usa"
FlaskValutazioneRequestHandler ..> Request

' Inbound Ports -> Services
ValutazionePort <|.. ValutazioneService

' Services -> Outbound Ports
ValutazioneService --> SessionCachePort

' Service -> Domain

ValutazioneService ..> Report : "modifica"

' Domain interno
Session o-- Report
Report o-- Device
Report o-- Model

' Outbound Adapter -> Port
SessionCachePort <|.. InMemorySessionCache


@enduml