@startuml Generate_Report
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100
skinparam packageStyle rectangle
skinparam style strictuml

package "Business Logic" {

  package "Logica di Dominio" {
    class Device {
    }

    class ReportDTO {
  
   }


  }

  package "Logica Applicativa" {
    class GenerateReportService {
      - device_repository: DeviceRepositoryPort
      - report_generator: ReportGeneratorPort
      + __init__(device_repository: DeviceRepositoryPort, report_generator: ReportGeneratorPort)
      + generate_report(device_id: string): bytes
    }
  }

  package "Inbound Ports" {
    interface GenerateReportPort <<interface>> {
      + generate_report(device_id: string): bytes
    }
  }

  package "Outbound Ports" {
    interface DeviceRepositoryPort <<interface>> {
      + get_device_by_id(device_id: string): Device
    }

    interface ReportGeneratorPort <<interface>> {
      + generate_report(report_dto: ReportDTO): bytes
    }
  }
}

package "Inbound Adapter" {
  class FlaskReportRequestHandler {
    - report_port: GenerateReportPort
    + __init__(report_port: GenerateReportPort)
    + generate_report()
  }

  class FlaskDownloadFileController <<Utility>> {
    + build_file_response(file_bytes: bytes, filename: string): FlaskResponse
  }
}

package "Outbound Adapter" {
  class PDFReportGenerator {
    + generate_report(report_dto: ReportDTO): bytes
  }
}

' --- Relazioni ---

' Inbound
FlaskReportRequestHandler --> GenerateReportPort : " usa"
FlaskReportRequestHandler ..> FlaskDownloadFileController

' Port -> Service
GenerateReportPort <|.. GenerateReportService

' Service -> Outbound Ports
GenerateReportService -down-> DeviceRepositoryPort
GenerateReportService -down-> ReportGeneratorPort

' Service -> Domain
GenerateReportService ..> Device : "recupera"
GenerateReportService ..> ReportDTO : "crea"

' Outbound Adapter -> Port
ReportGeneratorPort <|.. PDFReportGenerator

' Adapter -> DTO
PDFReportGenerator ..> ReportDTO : "riceve"



@enduml