@startuml Importazione_dispositivo_uc05_06

actor "Utente" as utente
participant "<<Boundary>>\nVue.js" as vue
participant "<<Inbound Adapter>>\nFlask API" as flask
participant "<<DTO>>\nImportDeviceDTO" as DTO
participant "<<Service>>\nDeviceService" as service
participant "<<Domain Entity>>\nDispositivo" as domain
participant "<<Outbound Adapter>>\npymongo : DeviceRepositoryPort" as repo

utente -> vue: Importazione dispositivo
activate vue

vue -> flask: POST /api/devices
activate flask

flask -> DTO: validazione_sintassi(JSON)
activate DTO

alt UC06 - Errore formato file
    DTO --> flask: ValidationError
    flask --> vue: HTTP 400 Bad Request
    vue --> utente: Errore: formato non valido
else Sintassi Corretta
    DTO --> flask: DTO_validato
end
deactivate DTO

flask -> service: importa_dispositivo(DTO_validato)
activate service

service -> domain: Dispositivo.create(dati_estratti_dal_dto)
activate domain

domain -> domain: verifica_regole_normative()
alt UC06 - Errore semantica file
    domain --> service: DomainException
    service --> flask: Eccezione Propagata
    flask --> vue: HTTP 422 Unprocessable Entity
    vue --> utente: Errore: il file viola la norma
else L'entità rispetta le regole di dominio
    domain --> service: nuovo_dispositivo
end
deactivate domain

service -> repo: salva(nuovo_dispositivo)
activate repo
repo --> service: id_dispositivo
deactivate repo

service --> flask: success(id_dispositivo)
deactivate service

flask --> vue: HTTP 201 Created
deactivate flask

vue --> utente: Dispositivo importato
deactivate vue

@enduml