@startuml
skinparam classAttributeIconSize 0   
    class EvaluateNodeCommand <<Command DTO>> {
        + session_id: String
        + asset_id: String
        + requirement_id: String
        + node_id: String
        + answer: Boolean
    }
@enduml
