@startuml
skinparam classAttributeIconSize 0


    class SaveAssetCommand {
        + asset_id:string
        + name:String
        + type:AssetType
        + description:String
        + session_id: String
    }

@enduml