#import "/src/config.typ":template_dir
== Introduzione strategie di testing \ 
 I test sono organizzati in categorie: 
- i Test di Sistema (TS), che verificano il comportamento del sistema a livello di singolo caso d'uso;
- i Test di Accettazione (TA), che validano i flussi operativi macroscopici dal punto di vista dell'utente finale.

== Test di Sistema (TS)
I test di sistema verificano in modo granulare ogni funzionalità del sistema, associando ciascun test a uno specifico caso d'uso. Lo stato NI (Non Implementato) indica che il test è definito ma non ancora eseguibile, in attesa dello sviluppo del PoC.
#show figure.where(kind: table): set block(breakable: true)
#figure(
  caption: [Test di Sistema],
  table(
    columns: (auto, 1fr, auto, auto),
    align: (center, left, center, center),6
    table.header(
      [*Codice Test*], [*Descrizione*], [*Caso d'Uso*], [*Stato*],  //anche se caso d'uso sarebbe meglio sostituire con requisiti
    ),
    [TS_001], [Verificare che il sistema gestisca l'Autenticazione], [UC01], [NI],
    [TS_002], [Verificare che il sistema permetta l'Inserimento username], [UC01.1], [NI],
    [TS_003], [Verificare che il sistema permetta l'Inserimento password], [UC01.2], [NI],
    [TS_004], [Verificare che il sistema gestisca l'Errore autenticazione], [UC02], [NI],
    [TS_005], [Verificare che il sistema permetta la Registrazione], [UC03], [NI],
    [TS_006], [Verificare che il sistema permetta l'Inserimento di un nuovo dispositivo], [UC04], [NI],
    [TS_007], [Verificare che il sistema permetta la Creazione di un nuovo dispositivo per la valutazione], [UC05], [NI],
    [TS_008], [Verificare l'Inserimento dati dispositivo], [UC05.1], [NI],
    [TS_009], [Verificare l'Inserimento nome dispositivo], [UC05.1.1], [NI],
    [TS_010], [Verificare l'Inserimento sistema operativo dispositivo], [UC05.1.2], [NI],
    [TS_011], [Verificare l'Inserimento versione firmware dispositivo], [UC05.1.3], [NI],
    [TS_012], [Verificare l'Inserimento funzionalità dispositivo], [UC05.1.4], [NI],
    [TS_013], [Verificare l'Inserimento descrizione dispositivo], [UC05.1.5], [NI],
    [TS_014], [Verificare il Caricamento di un dispositivo per la valutazione], [UC06], [NI],
    [TS_015], [Verificare la Selezione file sorgente], [UC06.1], [NI],
    [TS_016], [Verificare la Selezione file json], [UC06.1.1], [NI],
    [TS_017], [Verificare la Selezione file xml], [UC06.1.2], [NI],
    [TS_018], [Verificare la Selezione file csv], [UC06.1.3], [NI],
    [TS_019], [Verificare la gestione dell'Errore importazione file], [UC07], [NI],
    [TS_020], [Verificare la funzione Visualizza dati del dispositivo], [UC08], [NI],
    [TS_021], [Verificare la funzione Visualizza nome dispositivo], [UC08.1], [NI],
    [TS_022], [Verificare la funzione Visualizza sistema operativo dispositivo], [UC08.2], [NI],
    [TS_023], [Verificare la funzione Visualizza versione firmware dispositivo], [UC08.3], [NI],
    [TS_024], [Verificare la funzione Visualizza funzionalità dispositivo], [UC08.4], [NI],
    [TS_025], [Verificare la funzione Visualizza descrizione dispositivo], [UC08.5], [NI],
    [TS_026], [Verificare la funzione Visualizza versione dello standard], [UC08.6], [NI],
    [TS_027], [Verificare la Modifica di un dispositivo], [UC09], [NI],
    [TS_028], [Verificare la Modifica nome dispositivo], [UC09.1], [NI],
    [TS_029], [Verificare la Modifica sistema operativo dispositivo], [UC09.2], [NI],
    [TS_030], [Verificare la Modifica versione firmware dispositivo], [UC09.3], [NI],
    [TS_031], [Verificare la Modifica funzionalità dispositivo], [UC09.4], [NI],
    [TS_032], [Verificare la Modifica ambiente operativo], [UC09.5], [NI],
    [TS_033], [Verificare la Modifica descrizione dispositivo], [UC09.6], [NI],
    [TS_034], [Verificare la Modifica versione dello standard], [UC09.7], [NI],
    [TS_035], [Verificare la funzione Elimina dispositivo], [UC10], [NI],
    [TS_036], [Verificare la gestione dell'Annullamento creazione dispositivo], [UC11], [NI],
    [TS_037], [Verificare la Chiusura sessione di valutazione attuale], [UC12], [NI],
    [TS_038], [Verificare la Chiusura sessione di verifica attuale], [UC13], [NI],
    [TS_039], [Verificare la gestione dell'Errore durante il salvataggio automatico], [UC13.1], [NI],
    [TS_040], [Verificare la funzione Importa lista di file di asset], [UC14], [NI],
    [TS_041], [Verificare la funzione Importa file asset singolo], [UC15], [NI],
    [TS_042], [Verificare la gestione dell'Errore importazione file asset], [UC16], [NI],
    [TS_043], [Verificare la gestione dell'Importazione di asset appartenenti a uno standard diverso], [UC16.1], [NI],
    [TS_044], [Verificare la gestione dell'Errore struttura di alcuni asset non valida], [UC16.2], [NI],
    [TS_045], [Verificare la funzione Visualizza riepilogo di importazione], [UC17], [NI],
    [TS_046], [Verificare la gestione dell'Errore conflitto merge asset], [UC18], [NI],
    [TS_047], [Verificare la Risoluzione conflitto di merge], [UC19], [NI],
    [TS_048], [Verificare la funzione Visualizza lista asset], [UC20], [NI],
    [TS_049], [Verificare la funzione Visualizza asset singolo], [UC20.1], [NI],
    [TS_050], [Verificare la funzione Visualizza riepilogo requisiti], [UC20.2], [NI],
    [TS_051], [Verificare la funzione Vedi numero pass], [UC20.2.1], [NI],
    [TS_052], [Verificare la funzione Vedi numero fail], [UC20.2.2], [NI],
    [TS_053], [Verificare la funzione Vedi numero not applicable], [UC20.2.3], [NI],
    [TS_054], [Verificare la funzione Visualizza riepilogo risultati], [UC21], [NI],
    [TS_055], [Verificare la funzione Vedi numero di asset in sospeso], [UC21.1], [NI],
    [TS_056], [Verificare l'Aggiunta asset tramite interfaccia], [UC22], [NI],
    [TS_057], [Verificare l'Eliminazione di un asset], [UC23], [NI],
    [TS_058], [Verificare la Modifica asset], [UC24], [NI],
    [TS_059], [Verificare la funzione Cerca asset], [UC25], [NI],
    [TS_060], [Verificare la funzione Salva modifica asset], [UC26], [NI],
    [TS_061], [Verificare la gestione dell'Inserimento dati non validi], [UC27], [NI],
    [TS_062], [Verificare la funzione Esporta lista asset], [UC28], [NI],
    [TS_063], [Verificare la funzione Esporta lista asset .xml], [UC28.1], [NI],
    [TS_064], [Verificare la funzione Esporta lista asset .json], [UC28.2], [NI],
    [TS_065], [Verificare la funzione Esporta lista asset .csv], [UC28.3], [NI],
    [TS_066], [Verificare la funzione Esporta lista asset .pdf], [UC28.4], [NI],
    [TS_067], [Verificare la gestione dell'Errore nell'esportazione], [UC29], [NI],
    [TS_068], [Verificare la gestione dell'Errore nel salvataggio dei dati degli asset], [UC30], [NI],
    [TS_069], [Verificare la Consultazione requisito normativo], [UC31], [NI],
    [TS_070], [Verificare la funzione Visualizza descrizione del requisito], [UC31.1], [NI],
    [TS_071], [Verificare la funzione Visualizza razionale del requisito], [UC31.2], [NI],
    [TS_072], [Verificare la funzione Visualizza guida], [UC31.3], [NI],
    [TS_073], [Verificare la funzione Visualizza requisito], [UC32], [NI],
    [TS_074], [Verificare la funzione Visualizza l'asset di appartenenza], [UC32.1], [NI],
    [TS_075], [Verificare la funzione Visualizza codice del requisito], [UC32.2], [NI],
    [TS_076], [Verificare la funzione Visualizza nome del requisito], [UC32.3], [NI],
    [TS_077], [Verificare la funzione Visualizza stato aggregato del requisito], [UC32.4], [NI],
    [TS_078], [Verificare la funzione Visualizza lista di assessment unit], [UC32.5], [NI],
    [TS_079], [Verificare la funzione Visualizza elemento della lista di assessment unit], [UC32.5.1], [NI],
    [TS_080], [Verificare la funzione Visualizza assessment unit], [UC33], [NI],
    [TS_081], [Verificare la funzione Visualizza contesto di una assessment unit], [UC33.1], [NI],
    [TS_082], [Verificare la funzione Visualizza codice di una assessment unit], [UC33.2], [NI],
    [TS_083], [Verificare la funzione Visualizza tipo di una assessment unit], [UC33.3], [NI],
    [TS_084], [Verificare la funzione Visualizza nome di una assessment unit], [UC33.4], [NI],
    [TS_085], [Verificare la funzione Visualizza stato della valutazione assessment unit], [UC33.5], [NI],
    [TS_086], [Verificare la funzione Visualizza decision tree], [UC34], [NI],
    [TS_087], [Verificare la funzione Visualizza decision tree graficamente], [UC34.1], [NI],
    [TS_088], [Verificare la funzione Visualizza nodo decision tree], [UC34.2], [NI],
    [TS_089], [Verificare la funzione Visualizza codice del nodo], [UC34.2.1], [NI],
    [TS_090], [Verificare la funzione Visualizza domanda del nodo], [UC34.2.2], [NI],
    [TS_091], [Verificare la funzione Visualizza risposta del nodo], [UC34.2.3], [NI],
    [TS_092], [Verificare la funzione Visualizza evidenze del nodo], [UC34.2.4], [NI],
    [TS_093], [Verificare la funzione Visualizza info], [UC34.2.4.1], [NI],
    [TS_094], [Verificare la funzione Visualizza just], [UC34.2.4.2], [NI],
    [TS_095], [Verificare la Gestione della valutazione del DT], [UC35], [NI],
    [TS_096], [Verificare la Compilazione nodo], [UC35.1], [NI],
    [TS_097], [Verificare l'Aggiungi evidenze], [UC35.1.1], [NI],
    [TS_098], [Verificare l'Aggiungi just], [UC35.1.1.1], [NI],
    [TS_099], [Verificare l'Aggiungi info], [UC35.1.1.2], [NI],
    [TS_100], [Verificare la Selezione della risposta del nodo], [UC35.1.2], [NI],
    [TS_101], [Verificare la funzione Esegui decision tree], [UC36], [NI],
    [TS_102], [Verificare la gestione di un Decision tree non completo], [UC37], [NI],
    [TS_103], [Verificare la Navigazione del decision tree], [UC38], [NI],
    [TS_104], [Verificare la funzione Vai al nodo precedente], [UC38.1], [NI],
    [TS_105], [Verificare la funzione Nodo root], [UC38.1.1], [NI],
    [TS_106], [Verificare la funzione Vai al nodo successivo], [UC38.2], [NI],
    [TS_107], [Verificare la funzione Nodo foglia], [UC38.2.1], [NI],
    [TS_108], [Verificare la funzione Nodo senza risposta], [UC38.2.2], [NI],
    [TS_109], [Verificare la funzione Salva valutazione], [UC39], [NI],
    [TS_110], [Verificare la funzione Salva sul file corrente], [UC39.1], [NI],
    [TS_111], [Verificare la funzione Salva come nuovo file], [UC39.2], [NI],
    [TS_112], [Verificare la Valutazione del dispositivo], [UC40], [NI],
    [TS_113], [Verificare la Valutazione di un asset], [UC41], [NI],
    [TS_114], [Verificare la Valutazione di un requisito], [UC42], [NI],
    [TS_115], [Verificare la funzione Esporta risultato dell'esecuzione], [UC43], [NI],
    [TS_116], [Verificare la funzione Crea nuovo modello], [UC44], [NI],
    [TS_117], [Verificare la funzione Importa nuovo modello], [UC45], [NI],
    [TS_118], [Verificare la funzione Avvia sessione di modifica su modello esistente], [UC46], [NI],
    [TS_119], [Verificare la funzione Salva modifiche sul modello], [UC47], [NI],
    [TS_120], [Verificare la funzione Salva come nuovo modello], [UC48], [NI],
    [TS_121], [Verificare la funzione Scarta modifiche sul modello], [UC49], [NI],
    [TS_122], [Verificare la funzione Rimuovi modello], [UC50], [NI],
    [TS_123], [Verificare l'Inserisci nome del modello], [UC51], [NI],
    [TS_124], [Verificare la funzione Visualizza nome del modello], [UC52], [NI],
    [TS_125], [Verificare l'Inserisci codice del modello], [UC53], [NI],
    [TS_126], [Verificare la funzione Visualizza codice del modello], [UC54], [NI],
    [TS_127], [Verificare la Modifica anagrafica del modello], [UC55], [NI],
    [TS_128], [Verificare l'Aggiungi classe di asset], [UC56], [NI],
    [TS_129], [Verificare l'Inserisci nome di una classe di asset], [UC56.1], [NI],
    [TS_130], [Verificare l'Inserisci codice di una classe di asset], [UC56.2], [NI],
    [TS_131], [Verificare l'Inserisci descrizione di una classe di asset], [UC56.3], [NI],
    [TS_132], [Verificare la funzione Rimuovi classe di asset], [UC57], [NI],
    [TS_133], [Verificare la funzione Avvia modifica classe di asset], [UC58], [NI],
    [TS_134], [Verificare la Modifica anagrafica], [UC58.1], [NI],
    [TS_135], [Verificare la funzione Definisci attributo della classe], [UC58.2], [NI],
    [TS_136], [Verificare la Conferma modifica alla classe asset], [UC59], [NI],
    [TS_137], [Verificare l'Annulla modifica alla classe asset], [UC60], [NI],
    [TS_138], [Verificare l'Aggiungi nuovo requisito], [UC61], [NI],
    [TS_139], [Verificare l'Inserisci anagrafica del requisito], [UC61.1], [NI],
    [TS_140], [Verificare l'Inserisci codice], [UC61.1.1], [NI],
    [TS_141], [Verificare la gestione di un Errore codice duplicato], [UC61.1.1.1], [NI],
    [TS_142], [Verificare l'Inserisci nome del requisito], [UC61.1.2], [NI],
    [TS_143], [Verificare l'Inserisci descrizione normativa del requisito], [UC61.1.3], [NI],
    [TS_144], [Verificare l'Inserisci razionale del requisito], [UC61.1.4], [NI],
    [TS_145], [Verificare l'Inserisci linea guida], [UC61.1.5], [NI],
    [TS_146], [Verificare l'Inserimento target del requisito], [UC61.2], [NI],
    [TS_147], [Verificare l'Aggiungi dipendenza], [UC62], [NI],
    [TS_148], [Verificare la Rimuovi dipendenza], [UC63], [NI],
    [TS_149], [Verificare la gestione di un Errore dipendenza circolare], [UC64], [NI],
    [TS_150], [Verificare la funzione Avvia modifica di un requisito], [UC65], [NI],
    [TS_151], [Verificare la funzione Salva inserimenti del requisito], [UC66], [NI],
    [TS_152], [Verificare la funzione Scarta inserimenti del requisito], [UC67], [NI],
    [TS_153], [Verificare la funzione Rimuovi requisito], [UC68], [NI],
    [TS_154], [Verificare la funzione Avvia gestione del decision tree], [UC69], [NI],
    [TS_155], [Verificare l'Aggiungi nodo], [UC69.1], [NI],
    [TS_156], [Verificare l'Aggiungi nodo foglia], [UC69.1.1], [NI],
    [TS_157], [Verificare l'Aggiungi nodo pass], [UC69.1.1.1], [NI],
    [TS_158], [Verificare l'Aggiungi nodo fail], [UC69.1.1.2], [NI],
    [TS_159], [Verificare l'Aggiungi nodo not applicable], [UC69.1.1.3], [NI],
    [TS_160], [Verificare l'Aggiungi nodo di decisione], [UC69.1.2], [NI],
    [TS_161], [Verificare la funzione Rimuovi nodo], [UC69.2], [NI],
    [TS_162], [Verificare la Modifica nodo], [UC69.3], [NI],
    [TS_163], [Verificare l'Inserisci testo di una domanda], [UC69.3.1], [NI],
    [TS_164], [Verificare l'Inserisci descrizione dell'evidenza richiesta], [UC69.3.2], [NI],
    [TS_165], [Verificare la funzione Salva inserimenti al decision tree], [UC70], [NI],
    [TS_166], [Verificare la funzione Scarta inserimenti al decision tree], [UC71], [NI],
    [TS_167], [Verificare la gestione di una Struttura non valida dopo la modifica], [UC72], [NI],
    [TS_168], [Verificare il Salvataggio modifiche alla struttura dei dt], [UC73], [NI],
    [TS_169], [Verificare la gestione dell'Errore nel salvataggio della struttura del decision tree], [UC74], [NI],
    [TS_170], [Verificare la funzione Visualizza cronologia dei dispositivi valutati], [UC75], [NI],
  )
)

// manca test-> requisito tracciamento 

== Test di Accettazione (TA)
I test di accettazione verificano che il sistema soddisfi i requisiti dal punto di vista dell'utente, raggruppando i casi d'uso in flussi operativi completi e significativi. Ogni test rappresenta uno scenario d'uso realistico. Il superamento di questi test costituisce la condizione necessaria per il rilascio del prodotto.
#show figure.where(kind: table): set block(breakable: true)

typst#show figure.where(kind: table): set block(breakable: true)

#figure(
  caption: [Test di Accettazione],
  table(
    columns: (auto, 1fr, auto),
    align: (center + horizon, left + horizon, center + horizon),

    table.header(
      [*Codice Test*], [*Descrizione*], [*Stato*]
    ),

    [TA\_01], [Verificare che l'Utente possa autenticarsi o registrarsi per accedere alla propria area personale.], [NI],
    [TA\_02], [Verificare che l'Utente possa inserire a sistema un nuovo dispositivo da valutare, sia creandolo manualmente sia importandolo da file.], [NI],
    [TA\_03], [Verificare che l'Utente possa gestire l'intero ciclo di vita di un dispositivo (visualizzarne i dettagli, modificarne i dati o eliminarlo).], [NI],
    [TA\_04], [Verificare che l'Utente possa importare correttamente liste di asset nel sistema, gestendo eventuali conflitti di merge.], [NI],
    [TA\_05], [Verificare che l'Utente possa consultare e gestire l'elenco degli asset e visualizzare il riepilogo del loro stato di valutazione.], [NI],
    [TA\_06], [Verificare che l'Utente possa consultare la documentazione e i dettagli normativi associati a uno specifico requisito.], [NI],
    [TA\_07], [Verificare che l'Utente possa eseguire e navigare il Decision Tree per valutare un'assessment unit, compilando i nodi con relative risposte ed evidenze.], [NI],
    [TA\_08], [Verificare che l'Utente possa completare la sessione di valutazione di un dispositivo, salvarne lo stato ed esportare il report dei risultati.], [NI],
    [TA\_09], [Verificare che l'Utente possa creare o importare un intero nuovo modello normativo standard nel sistema.], [NI],
    [TA\_10], [Verificare che l'Utente possa avviare una sessione di modifica su un modello per alterarne l'anagrafica e salvare le modifiche.], [NI],
    [TA\_11], [Verificare che l'Utente possa strutturare le classi di asset di un modello (aggiunta, modifica, eliminazione e definizione degli attributi).], [NI],
    [TA\_12], [Verificare che l'Utente possa configurare i requisiti del modello, impostandone target e dipendenze.], [NI],
    [TA\_13], [Verificare che l'Utente possa strutturare l'albero decisionale (Decision Tree) di un requisito, aggiungendo e modificando nodi decisionali e nodi foglia.], [NI],
  )
)
