@startuml Modello_di_Dominio
skinparam linetype ortho
skinparam packageStyle rectangle


package "1. Evaluation Object" {
    !include Device.puml
    !include Asset.puml
    !include AssetType.puml
    !include Answer.puml
}

package "3. Compliance Standard" {
    !include ComplianceStandard.puml
    !include DecisionNode.puml
    !include Node.puml
    !include LeafNode.puml
    !include DecisionTree.puml
    !include Requirement.puml


}
package "2. Evaluation" {
    !include EvaluationSheet.puml
    !include EvaluationState.puml
    !include Verdict.puml
}

package "4. Session" {
    !include EvaluationSession.puml
    !include SessionType.puml
    !include SessionHandler.puml
}



@enduml