@startuml Asset
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Asset {
    - id: String
    - name: String
    - type: AssetType
    - description: String
}

Asset *-- "1..*" Answer

@enduml