@startuml DecisionNode
skinparam linetype ortho
skinparam classAttributeIconSize 0

class DecisionNode {
    - question: String
    + get_next_node(answer: Boolean): Node
}
DecisionNode *--" yes_child \n no_child" Node
DecisionNode --|> Node

@enduml