@startuml Device
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Device {
    - id: String
    - name: String
    - operating_system: String
    - description: String
    - assets: List<Asset>

    + add_asset(asset: Asset): void
    + remove_asset(asset_id: String): void
}

Device *-- "1..*" Asset

@enduml