@startuml EvaluationSheet
skinparam linetype ortho
skinparam classAttributeIconSize 0

class EvaluationSheet {
    ' - complianceStandard: ComplianceStandard
    ' - device: Device

    + <<Create>> EvaluationSheet(device: Device, standard: ComplianceStandard): EvaluationSheet

    + evaluateRequirements(assetId: String, requirementsId: String): EvaluationState
    + evaluateAsset(assetId: String): EvaluationState
    + evaluateDevice(): EvaluationState
}
EvaluationSheet --> Device
EvaluationSheet --> ComplianceStandard
@enduml