@startuml EvaluationSession
skinparam linetype ortho
skinparam classAttributeIconSize 0

class EvaluationSession {
    ' - evaluationSheet: EvaluationSheet
    - session_id: String
    - session_type: SessionType
}
EvaluationSession --> EvaluationSheet
@enduml