@startuml EvaluationSheet
skinparam linetype ortho
skinparam classAttributeIconSize 0

class EvaluationSheet {
    ' - compliance_standard: ComplianceStandard
    ' - device: Device

    + __init__ (device: Device, standard: ComplianceStandard): EvaluationSheet

    + evaluate_requirements(asset_id: String, requirements_id: List<String>): EvaluationState
    + evaluate_asset(assetId: String): EvaluationState
    + evaluate_device(): EvaluationState
}
EvaluationSheet --> Device
EvaluationSheet --> ComplianceStandard
@enduml