@startuml Session
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Session {
    ' - evaluationSheet: EvaluationSheet
    - session_id: String
    - session_type: SessionType
}
Session --> EvaluationSheet
@enduml