@startuml ConcreteFileStandardImporterFactory
skinparam classAttributeIconSize 0
class ConcreteFileStandardImporterFactory {
    + get_file_standard_importer(extension: AllowedStandardFileExtension): FileStandardImporterPort
}

@enduml