@startuml InMemoryEvaluationSessionCache
skinparam classAttributeIconSize 0

class InMemoryEvaluationSessionCache {
    - session: EvaluationSession
    + create_evaluation_session(standard: ComplianceStandard, device: Device): EvaluationSession
    + get_evaluation_session(session_id: String): EvaluationSession
    + save_evaluation_session(session: EvaluationSession): void
    + has_active_session(): bool
    + close_evaluation_session(session_id: String): void
}

@enduml