@startuml MongoComplianceStandardAdapter
skinparam classAttributeIconSize 0

class MongoComplianceStandardAdapter <<Mongo Repository>> {
    - _collection: Collection
    + find_standard(standard_id: String): ComplianceStandard
    - _from_document(doc: Dict): ComplianceStandard
}

@enduml