@startuml PdfReportGeneratorAdapter
skinparam classAttributeIconSize 0
class PdfReportGenerator <<Report Adapter>> {
        + generate_report(device_evaluation: DeviceEvaluationDetail): IO[bytes]
    }
@enduml