@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class AsyncButton <<component>> {
  + action : Function
  + label : String
  + loadingLabel : String
  + buttonClass : String
  - isLoading : Boolean
  - error : String
  --
  + AsyncButton(action : Function, label : String, loadingLabel : String, buttonClass : String)
  - handleClick() : void
  + success(result) <<emit>>
  + error(err) <<emit>>
}

@enduml