@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class Toast <<component>> {
  - message : String
  - duration : String
  + Toast(message : String, duration : Number)
  + close() <<emit>>
}

@enduml