@startuml FlaskEvaluateDecisionNodeController
skinparam classAttributeIconSize 0
class FlaskEvaluateDecisionNodeController <<Flask Blueprint>> {
    + insert_decision_node_evaluation(req: Request): Response
}

@enduml