@startuml FlaskWriteDeviceController
skinparam classAttributeIconSize 0
class FlaskWriteDeviceController <<Flask Blueprint>> {
    + create_device(req: Request): Response
    + update_device(req: Request): Response
    + delete_device(req: Request): Response
}

@enduml