@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class DecisionTreeStore{

        - evaluationEngine: EvaluationEngine 
        - apiClient: EvaluationAPIClient 
+ answers: Map<string, boolean>
    + selectedNodeId: string | null
    + isSideBarOpen: boolean
    + activePath: string[]
    + layoutResult: LayoutResult | null
    + evaluationState: string | null
    + justification: string
    + justificationStatus: string
    + requirementsUrl: string
    + selectedNodeData: NodeDTO | null

    - refreshPath()
    - calculateLayout()
    + init(treeData:TreeStructure, savedAnswers:Map<String,Boolean>,justification:String,apiClient:EvaluationAPIClient,requirementsUrl:String)
    + setAnswer(nodeId: string, answer: boolean)
    + selectNode(nodeId: string
    + closeSideBar()
    + saveJustification(text: string)

}

@enduml