@startuml SessionClose

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 120
skinparam classAttributeIconSize 0
skinparam PackagePadding 30
skinparam style strictuml

package "Entry Point" {
    note "main.js legge attributi data-*\ndal DOM e monta SessionCloseWidget" as EntryNote
}

package "Smart Widget" {
    !include ../widget/SessionCloseWidget.puml
}

package "Componenti Dumb" {
    !include ../componenti_base/BaseModal.puml
    !include ../componenti_base/asyncButton.puml
}

SessionCloseWidget *-- BaseModal   : compone
SessionCloseWidget *-- AsyncButton : compone

@enduml