@startuml CloseEvaluationSessionService
skinparam classAttributeIconSize 0
class CloseEvaluationSessionService <<Application Service>> {
    + close(command: CloseEvaluationSessionCommand): void
}
@enduml