@startuml GetDeviceDashboardService
skinparam classAttributeIconSize 0
class GetDeviceDashboardService <<Application Service>> {
    + get_device_dashboard(session_id: String): DashboardDTO
}

@enduml