@startuml GetRequirementService
skinparam classAttributeIconSize 0

class GetRequirementService <<Application Service>> {
    + get_requirement(command: GetRequirementCommand): RequirementResponse
}

@enduml