@startuml GetRequirementService
skinparam classAttributeIconSize 0
class GetRequirementService <<Application Service>> {
    + get_requirement(query: GetRequirementQuery): RequirementResponse
}

@enduml