@startuml ImportStandardService
skinparam classAttributeIconSize 0
class ImportStandardService <<Application Service>> {
    - standard_repository: StandardRepositoryPort
    - standard_importer_factory: FileStandardImporterFactoryPort
    + __init__(standard_importer_factory: FileStandardImporterFactoryPort, standard_repository: StandardRepositoryPort)
    + import_standard(command: ImportStandardCommand): void
}

@enduml