@startuml OpenEvaluationSessionService
skinparam classAttributeIconSize 0
class OpenEvaluationSessionService <<Application Service>> {
    + open(command: OpenEvaluationSessionCommand): String
}

@enduml