@startuml OpenEvaluationSessionService
skinparam classAttributeIconSize 0
class OpenEvaluationSessionService <<Application Service>> {
    + open(device_id: String, session_id: String): String
}

@enduml