@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class EdgeDTO  {
    + id: string
    + sourceId: string
    + targetId: string
    + startX: Number
    + startY: Number
    + endX: Number
    + endY: Number
    + label: string
}
@enduml