@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class LayoutResult << (T,#87CEFA) typedef >> {
    + nodes: NodeDTO[]
    + edges: EdgeDTO[]
}


@enduml