@startuml asset-write-service
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 120
skinparam classAttributeIconSize 0
package "Inbound Adapter"{
class FlaskAssetWriteController <<Flask Blueprint>>{
        + __init__(asset_query_use_case:AssetQueryUseCase)
        + create_asset():Response
        + update_asset():Response
        + delete_asset():Response 
        ' + get_asset_by_id():Response

} 
  class Request <<Flask>> {
  }

  note right of Request
    Oggetto globale di Flask.
    Accessibile tramite import
    nei metodi dei request handler
    per estrarre i dati della
    richiesta HTTP corrente.
  end note

  FlaskAssetWriteController ..> Request
}



package "Application Core" {

        package "Inbound Port"{

                interface AssetWriteUseCase <<interface>>{
                                + create_asset(create_data:CreateAssetDTO):bool
                                + update_asset(update_data:UpdateAssetDTO):bool
                                + delete_asset(id:string):bool
                }
                
        }
                class AssetWriteService {
                        __init__(session_cache_port:SessionCachePort)
                                + create_asset(create_data:CreateAssetDTO):bool
                                + update_asset(update_data:UpdateAssetDTO):bool
                                + delete_asset(id:string):bool
                }
                
        package Domain {
                class Device
                class CreateAssetDTO{
                        name:String
                        AssetType:AssetType
                        description:String
                }
                class UpdateAssetDTO{
                        asset_id:string
                        name:String
                        AssetType:AssetType
                        description:String
                }
        }


        package "Outbound Ports"{
                !include ports/out/EvaluationSessionCachePort.puml

        }
}


FlaskAssetWriteController --> AssetWriteUseCase

AssetWriteService --> EvaluationSessionCachePort


AssetWriteService -up-|> AssetWriteUseCase



@enduml