@startuml device-query
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    class DeviceQueryController <<Flask Blueprint>> {
        - query_use_case: DeviceQueryUseCase

        + get_device_list(): Response
        + get_device_detail(): Response


    }
}

package "Application Core" {

    interface DeviceQueryUseCase <<Inbound Port>> {
        + get_device_list(): List<Device>
        + get_device_detail(device_id: String): Device
    }

 !include ports/out/DeviceReadRepositoryPort.puml

    class DeviceQueryService <<Application Service>> {
        - repository: DeviceReadRepositoryPort

        + get_device_list(): List<Device>
        + get_device_detail(device_id: String): Device
    }

    '!include ./Dominio/Device.puml

    DeviceQueryUseCase <|.. DeviceQueryService : "implementa"
    DeviceQueryService -down-( DeviceReadRepositoryPort : "richiede"

    DeviceQueryService ..> Device : "legge e restituisce"
}

package "Outbound Adapter" {
    class MongoDeviceAdapter <<Mongo Repository>> {
        - collection: pymongo.Collection

        + save(device: Device): void
        + delete_by_id(id: String): void

        + find_by_id(id: String): Device
        + find_all(): List<DeviceDTO>
    }
}

DeviceQueryController -( DeviceQueryUseCase : "utilizza"
DeviceReadRepositoryPort <|.. MongoDeviceAdapter : "implementa"

@enduml