@startuml device-write
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    class DeviceWriteController <<Flask Blueprint>> {

        - write_use_case: DeviceWriteUseCase

        + create_device(): Response
        + modify_device(): Response
        + delete_device(): Response
    }
}

package "Application Core" {
    class CreateDeviceDTO {
        + device_name: String
        + device_os: String
        + device_description: String
        + device_compliance_standard_id: String
    }

    class ModifyDeviceDTO {
        + device_id: String
        + device_name: String
        + device_os: String
        + device_description: String
    }

    '!include ./Dominio/Device.puml

    interface DeviceWriteUseCase <<Inbound Port>> {
        + create_device(dto: CreateDeviceDTO): bool
        + modify_device(dto: ModifyDeviceDTO): bool
        + delete_device(device_id: String): bool
    }

    !include ports/out/DeviceWriteRepositoryPort.puml

    class DeviceWriteService <<Application Service>> {
        - repository: DeviceWriteRepositoryPort
        + create_device(CreateDeviceDTO): bool
        + modify_device(ModifyDeviceDTO): bool
        + delete_device(deviceId: String): bool
    }

    DeviceWriteUseCase <|.. DeviceWriteService : "implementa"
    DeviceWriteService --( DeviceWriteRepositoryPort: "richiede"
    DeviceWriteService .right.> Device: "manipola"

}

package "Outbound Adapter" {
    class MongoDeviceAdapter <<Mongo Repository>> {
        - collection: pymongo.Collection
        + save(device: Device): void
        + find_by_id(id: String): Device
        + delete_by_id(id: String): void
        + find_all(): List<DeviceDTO>
    }
}

DeviceWriteController --( DeviceWriteUseCase: "utilizza"

DeviceWriteRepositoryPort <|.. MongoDeviceAdapter: "implementa"

@enduml