@startuml import-device
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100
skinparam packageStyle rectangle
skinparam style strictuml

package "Application Core" {

  package "Domain" {
    class Device {
    }
  }

  class ImportDeviceService {
    - device_importer_factory: FileDeviceImporterFactoryPort
    - device_repository: DeviceRepositoryPort
    + __init__(device_importer_factory: FileDeviceImporterFactoryPort, device_repository: DeviceRepositoryPort)
    + import_device(device_file_content: BinaryIO, extension: AllowedDeviceFileExtension): bool
  }

  enum AllowedDeviceFileExtension <<enum>> {
    CSV
    XML
    JSON
  }
}

package "Inbound Ports" {
  interface ImportDeviceUseCase <<interface>> {
    + import_device(device_file_content: BinaryIO, extension: AllowedDeviceFileExtension): bool
  }
}

package "Outbound Ports" {
  interface FileDeviceImporterPort <<interface>> {
    + parse_device_file(device_file_content: BinaryIO): Device
  }

  interface DeviceWriteRepositoryPort <<interface>> {
    + save(device: Device): bool
  }

  interface FileDeviceImporterFactoryPort <<interface>> {
    + get_file_device_importer(extension: AllowedDeviceFileExtension): FileDeviceImporterPort
  }
}

package "Inbound Adapter" {
  class ImportDeviceController <<Flask Blueprint>> {
    ' - import_port: ImportDeviceUseCase
    + __init__(import_port: ImportDeviceUseCase)
    + import_device()
  }

  class UploadFileController <<Utility>> {
    + get_http_file_payload(): BinaryIO
    + get_http_file_extension(): string
  }
}

package "Outbound Adapter" {
  abstract class FileDeviceImporter <<Template Method>> {
    + parse_device_file(device_file_content: BinaryIO): Device
    # check_metadata()
    # open_stream()
    # parse_data()
    # close_stream()
  }

  class CSVFileDeviceImporter {
    # check_metadata()
    # open_stream()
    # parse_data()
    # close_stream()
  }

  class JSONFileDeviceImporter {
    # check_metadata()
    # open_stream()
    # parse_data()
    # close_stream()
  }

  class XMLFileDeviceImporter {
    # check_metadata()
    # open_stream()
    # parse_data()
    # close_stream()
  }

  class ConcreteFileDeviceImporterFactory {
    + get_file_device_importer(extension: AllowedDeviceFileExtension): FileDeviceImporterPort
  }
}

' --- Relazioni ---

' Inbound
ImportDeviceController --> ImportDeviceUseCase : " usa"
ImportDeviceController .up.> UploadFileController

' Port -> Service
ImportDeviceUseCase <|.. ImportDeviceService

' Service -> Outbound Ports
ImportDeviceService -down-> FileDeviceImporterFactoryPort
ImportDeviceService -down-> DeviceWriteRepositoryPort

' Factory
FileDeviceImporterFactoryPort <|.. ConcreteFileDeviceImporterFactory
FileDeviceImporterFactoryPort ..> FileDeviceImporterPort
ConcreteFileDeviceImporterFactory .up.> CSVFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> JSONFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> XMLFileDeviceImporter

' Importer hierarchy
FileDeviceImporterPort <|.. FileDeviceImporter
FileDeviceImporter <|-down- CSVFileDeviceImporter
FileDeviceImporter <|-down- XMLFileDeviceImporter
FileDeviceImporter <|-down- JSONFileDeviceImporter

@enduml