@startuml AssetEvaluationDTO
skinparam linetype ortho
skinparam ClassAttributeIconSize 0

class RequirementEvaluationSummaryDTO {
    + id: String
    + evaluation: EvaluationState
}

class AssetEvaluationDTO {
    + name: String
    + type: AssetType
    + evaluation: EvaluationState
    + description: String
    + requirements: tuple[RequirementEvaluationSummaryDTO, ...]
}

AssetEvaluationDTO *-- "0..*" RequirementEvaluationSummaryDTO