// FILE GENERATO AUTOMATICAMENTE - NON MODIFICARE
// Lista dei file inclusi in ordine

#include "UC01_autenticazione.typ"
#include "UC01.1_inserimento_username.typ"
#include "UC01.2_inserimento_password.typ"
#include "UC02_errore_autenticazione.typ"
#include "UC03_seleziona_file.typ"
#include "UC03.1_seleziona_file_con_filtri.typ"
#include "UC03.1.1_file_con_estensione_non_permessa.typ"
#include "UC03.2_selezione_con_drag_and_drop.typ"
#include "UC03.2.1_drag_and_drop_fuori_dalla_drop_zone.typ"
#include "UC04_annulla_selezione.typ"
#include "UC05_errore_nella_selezione.typ"
#include "UC06_importa_lista_di_file_di_asset.typ"
#include "UC06.1_conferma_termine_selezione_file_asset.typ"
#include "UC06.2_importa_file_asset_singolo.typ"
#include "UC06.2.1_importa_json.typ"
#include "UC06.2.1.1_struttura_json_non_valida.typ"
#include "UC06.2.2_importa_xml.typ"
#include "UC06.2.2.1_struttura_xml_non_valida.typ"
#include "UC06.2.3_importa_csv.typ"
#include "UC06.2.3.1_struttura_csv_non_valida.typ"
#include "UC06.3_errore_import_file_asset.typ"
#include "UC06.3.1_errore_file_vuoto.typ"
#include "UC06.3.2_errore_file_troppo_grande.typ"
#include "UC06.3.3_errore_estensione_non_valida.typ"
#include "UC07_errore_conflitto_merge_asset.typ"
