@startuml ExportReportController
skinparam classAttributeIconSize 0
class ExportReportController {
    + export_report(req: Request): Response
}

class DownloadFileController <<Utility>> {
    + build_file_response(file_bytes: bytes, filename: string): FlaskResponse
}
ExportReportController .r.> DownloadFileController

@enduml