@startuml ExportStandardController

class ExportStandardController <<Flask Blueprint>> {
    + export_standard(): Response
}
class DownloadFileController <<Utility>> {
    + build_file_response(file_bytes: bytes, filename: string): FlaskResponse
}
ExportStandardController .r.> DownloadFileController

@enduml