@startuml DownloadFileController
skinparam classAttributeIconSize 0
class ExportDeviceController <<Flask Blueprint>> {
    - export_uc: ExportDeviceUseCase
    + export_device(req: Request): Response
}
class DownloadFileController <<Utility>> {
    + build_file_response(file_bytes: bytes, filename: string): FlaskResponse
}
ExportDeviceController .r.> DownloadFileController

@enduml