@startuml UploadFileController
skinparam classAttributeIconSize 0

class UploadFileController <<Utility>> {
    + get_http_file_payload(): BinaryIO
    + get_http_file_extension(): string
}



@enduml