@startuml WriteDeviceController

class WriteDeviceController <<Flask Blueprint>> {
    + create_device(req: Request): Response
    + save_device(req: Request): Response
    + delete_device(req: Request): Response
}