@startuml WriteDeviceController

class WriteDeviceController <<Flask Blueprint>> {
    - create_use_case: WriteDeviceUseCase
    - save_use_case: SaveDeviceUseCase
    - delete_use_case: DeleteDeviceUseCase

    + create_device(req: Request): Response
    + save_device(req: Request): Response
    + delete_device(req: Request): Response
}