@startuml CreateDevice
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteDeviceController.puml
}

package "Application Core" {

    class CreateDeviceCommand {
        + device_name: String
        + device_os: String
        + device_description: String
        + compliance_standard_id: String
    }
    
    () "CreateDeviceUseCase" as CreateDeviceUseCase
    !include ApplicationServices/CreateDeviceService.puml
    !include Domain/Device.puml
    () "RegisterDevicePort" as RegisterDevicePort

    CreateDeviceUseCase .right.> CreateDeviceCommand
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}


CreateDeviceService - CreateDeviceUseCase


CreateDeviceService ---( RegisterDevicePort : usa

WriteDeviceController --( CreateDeviceUseCase : usa
MongoDeviceAdapter - RegisterDevicePort

@enduml