@startuml CreateAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/FlaskWriteAssetController.puml
}

package "Application Core" {

    !include Command/CreateAssetCommand.puml

    () "CreateAssetUseCase"
    !include ApplicationServices/CreateAssetService.puml
    !include Domain/Asset.puml
    () "SaveEvaluationSessionPort"
    () "GetEvaluationSessionPort"

    CreateAssetService .left.> CreateAssetCommand: legge
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


CreateAssetService - CreateAssetUseCase


CreateAssetService --> SaveEvaluationSessionPort : usa
CreateAssetService --> GetEvaluationSessionPort : usa

SaveEvaluationSessionPort -- InMemoryEvaluationSessionCache
GetEvaluationSessionPort -- InMemoryEvaluationSessionCache

FlaskWriteAssetController --> CreateAssetUseCase : usa

@enduml