@startuml CreateDevice
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteDeviceController.puml
}

package "Application Core" {

    class CreateDeviceCommand <<Command DTO>> {
        + device_name: String
        + device_os: String
        + device_description: String
        + compliance_standard_id: String
    }
    
    () "CreateDeviceUseCase" as CreateDeviceUseCase
    !include ApplicationServices/CreateDeviceService.puml
    !include Domain/Device.puml
    () "SaveDevicePort" as SaveDevicePort
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}


CreateDeviceService - CreateDeviceUseCase


CreateDeviceService --( SaveDevicePort : usa

WriteDeviceController --( CreateDeviceUseCase : usa
MongoDeviceAdapter - SaveDevicePort

@enduml