@startuml CreateAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    class CreateAssetCommand <<Command DTO>> {
        name:String
        AssetType:AssetType
        description:String
    }

    () "CreateAssetUseCase"
    !include ApplicationServices/CreateAssetService.puml
    !include Domain/Asset.puml
    () "SaveSessionPort"
    () "GetSessionPort"
    () "EvaluationSessionPort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


CreateAssetService - CreateAssetUseCase


CreateAssetService --( SaveSessionPort : usa
CreateAssetService --( GetSessionPort : usa

SaveSessionPort -- EvaluationSessionPort
GetSessionPort -- EvaluationSessionPort

WriteAssetController --( CreateAssetUseCase : usa
InMemoryEvaluationSessionCache - EvaluationSessionPort

@enduml