@startuml DeleteAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    class DeleteAssetCommand <<Command DTO>> {
        + asset_id: String
    }

    () "DeleteAssetUseCase"
    !include ApplicationServices/DeleteAssetService.puml
    !include Domain/Asset.puml
    () "SaveSessionPort"
    () "GetSessionPort"
    () "EvaluationSessionPort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


DeleteAssetService - DeleteAssetUseCase

DeleteAssetService --( SaveSessionPort : usa
DeleteAssetService --( GetSessionPort : usa

SaveSessionPort -- EvaluationSessionPort
GetSessionPort -- EvaluationSessionPort

WriteAssetController --( DeleteAssetUseCase : usa
InMemoryEvaluationSessionCache - EvaluationSessionPort

@enduml