@startuml DeleteAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {
    () "DeleteAssetUseCase"
    !include ApplicationServices/DeleteAssetService.puml
    !include Domain/Asset.puml
    () "SaveSessionPort"
    () "GetSessionPort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

' Aggiunte direzioni esplicite (-down-) per forzare l'allineamento verticale corretto
WriteAssetController -down-> DeleteAssetUseCase : usa
DeleteAssetUseCase -down- DeleteAssetService

DeleteAssetService -down-> SaveSessionPort : usa
DeleteAssetService -down-> GetSessionPort : usa

SaveSessionPort -down- InMemoryEvaluationSessionCache
GetSessionPort -down- InMemoryEvaluationSessionCache

@enduml