@startuml DeleteAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    () "DeleteAssetUseCase"
    !include ApplicationServices/DeleteAssetService.puml
    !include Domain/Asset.puml
    !include Domain/EvaluationSession.puml
    () "SaveSessionPort"
    () "GetSessionPort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


DeleteAssetService - DeleteAssetUseCase

DeleteAssetService --> SaveSessionPort : usa
DeleteAssetService --> GetSessionPort : usa

SaveSessionPort -- InMemoryEvaluationSessionCache
GetSessionPort -- InMemoryEvaluationSessionCache

WriteAssetController --> DeleteAssetUseCase : usa

@enduml