@startuml ExportDevice
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packagePadding 20

package "Inbound Adapter" {
    !include InboundAdapters/ExportDeviceController.puml
}

package "Application Core" {

    class ExportDeviceCommand {
        + device_id: String
        + extension: AllowedDeviceFileExtension
    }

    enum AllowedDeviceFileExtension <<enum>> {
        XML
        JSON
        CSV
    }
    
    () "ExportDeviceUseCase" as ExportDeviceUseCase

    !include ApplicationServices/ExportDeviceService.puml

    class DeviceFileCommand {
        + device_name: String
        + device_os_name: String
        + device_description: String
        + model_id: String
        + model_name: String
        + model_version: String
        + assets: List<AssetFileCommand>
    }

    class AssetFileCommand {
        + asset_name: String
        + asset_type: AssetType
        + asset_description: String
        + assessments: List<AssessmentFileCommand>
    }

    class AssessmentFileCommand {
        + requirement_code: String
        + answers: Dictionary<String, bool>
    }

    () "FindDevicePort" as FindDevicePort
    () "FileDeviceExporterFactoryPort" as FileDeviceExporterFactoryPort
    () "FileDeviceExporterPort" as FileDeviceExporterPort

    FileDeviceExporterFactoryPort -[hidden]right- FileDeviceExporterPort

    !include Domain/Device.puml


    ExportDeviceUseCase -down- ExportDeviceService
    
    AllowedDeviceFileExtension -[hidden]left- ExportDeviceUseCase

    ExportDeviceCommand -[hidden]right- ExportDeviceService
    ExportDeviceService .left.> ExportDeviceCommand : legge
    ExportDeviceService .down.> DeviceFileCommand : popola

    DeviceFileCommand *-- AssetFileCommand
    AssetFileCommand *-- AssessmentFileCommand
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
    !include OutboundAdapters/ConcreteFileDeviceExporterFactory.puml
    !include OutboundAdapters/FileDeviceExporter.puml

    class JSONFileDeviceExporter {
        # prepare_structure()
        # write_data()
        # finalize_output()
    }

    class XMLFileDeviceExporter {
        # prepare_structure()
        # write_data()
        # finalize_output()
    }

    FileDeviceExporter <|-down- JSONFileDeviceExporter
    FileDeviceExporter <|-down- XMLFileDeviceExporter

    ConcreteFileDeviceExporterFactory ..> JSONFileDeviceExporter : crea
    ConcreteFileDeviceExporterFactory ..> XMLFileDeviceExporter : crea
}


ExportDeviceController -down-> ExportDeviceUseCase : usa

ExportDeviceService -right-> FindDevicePort : usa
ExportDeviceService -down-> FileDeviceExporterFactoryPort : usa
ExportDeviceService -down---> FileDeviceExporterPort : usa


MongoDeviceAdapter -left- FindDevicePort
ConcreteFileDeviceExporterFactory -left- FileDeviceExporterFactoryPort
FileDeviceExporter -left- FileDeviceExporterPort

@enduml