@startuml ExportDevice
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packagePadding 20

package "Inbound Adapter" {
    !include InboundAdapters/ExportDeviceController.puml
}

package "Application Core" {

    class ExportDeviceCommand {
        + device_id: String
        + extension: AllowedDeviceFileExtension
    }

    enum AllowedDeviceFileExtension <<enum>> {
        XML
        JSON
        CSV
    }
    
    () "ExportDeviceUseCase" as ExportDeviceUseCase

    !include ApplicationServices/ExportDevic    eService.puml

    class ExportedFile {
        + content: Bytes
        + filename: String
        + media_type: String
    }

    () "FindDevicePort" as FindDevicePort
    () "FileDeviceExporterFactoryPort" as FileDeviceExporterFactoryPort
    () "FileDeviceExporterPort" as FileDeviceExporterPort

    FileDeviceExporterFactoryPort -[hidden]right- FileDeviceExporterPort

    !include Domain/Device.puml


    ExportDeviceUseCase -down- ExportDeviceService
    
    AllowedDeviceFileExtension -[hidden]left- ExportDeviceUseCase

    ExportDeviceCommand -[hidden]right- ExportDeviceService
    ExportDeviceService .left.> ExportDeviceCommand : legge
    ExportDeviceService .down.> ExportedFile : popola
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
    !include OutboundAdapters/ConcreteFileDeviceExporterFactory.puml
    !include OutboundAdapters/FileDeviceExporter.puml

    class JSONFileDeviceExporter {
        # prepare_structure()
        # write_data()
        # finalize_output()
    }

    class XMLFileDeviceExporter {
        # prepare_structure()
        # write_data()
        # finalize_output()
    }

    class CSVFileDeviceExporter {
        # prepare_structure()
        # write_data()
        # finalize_output()
    }

    FileDeviceExporter <|-down- JSONFileDeviceExporter
    FileDeviceExporter <|-down- XMLFileDeviceExporter
    FileDeviceExporter <|-down- CSVFileDeviceExporter

    ConcreteFileDeviceExporterFactory ..> JSONFileDeviceExporter : crea
    ConcreteFileDeviceExporterFactory ..> XMLFileDeviceExporter : crea
    ConcreteFileDeviceExporterFactory ..> CSVFileDeviceExporter : crea
}


ExportDeviceController -down-> ExportDeviceUseCase : usa

ExportDeviceService -right-> FindDevicePort : usa
ExportDeviceService -down-> FileDeviceExporterFactoryPort : usa
ExportDeviceService -down---> FileDeviceExporterPort : usa


MongoDeviceAdapter -left- FindDevicePort
ConcreteFileDeviceExporterFactory -left- FileDeviceExporterFactoryPort
FileDeviceExporter -left- FileDeviceExporterPort

@enduml