@startuml ExportReport

skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 120
skinparam classAttributeIconSize 0
skinparam PackagePadding 30

package "Inbound Adapter" {
    class ExportReportController {
        +export_report(req: Request): Response
    }
    
    class DownloadFileController <<Utility>> {
        +build_file_response(file_bytes: bytes, filename: string): FlaskResponse
    }
    
    ExportReportController .right.> DownloadFileController
}

package "Application Core" {

    () "ExportReportUseCase"

    class ExportReportService {
        +export(command: ExportReportCommand): bytes
    }

    class ExportReportCommand {
        +session_id: String
        +format: ReportFormat
    }

    () "ReportGeneratorPort"
    () "GetEvaluationSessionPort"

   
    ExportReportService -[hidden]right- ExportReportCommand
    ReportGeneratorPort -[hidden]right- GetEvaluationSessionPort

 
    ExportReportService -up- ExportReportUseCase
    ExportReportService .right.> ExportReportCommand : legge
    
    
    ExportReportService -down-> ReportGeneratorPort : usa
    ExportReportService -down-> GetEvaluationSessionPort : usa
    

}

package "Outbound Adapter" {
    class PdfReportGeneratorAdapter <<Report Adapter>> {
        +generate_report(session: EvaluationSession): bytes
        #format_header()
        #print_asset_evaluations()
        #format_footer()
    }

    class InMemoryEvaluationSessionCache {
        -sessions: dictionary[string:EvaluationSession]
        +create_session(): EvaluationSession
        +delete_session(session_id: String): void
        +get_session(session_id: String): EvaluationSession
        +save_session(session: EvaluationSession): void
        +has_active_session(device_id: String): bool
    }
}


ExportReportController -down-> ExportReportUseCase : usa

PdfReportGeneratorAdapter -up- ReportGeneratorPort 
InMemoryEvaluationSessionCache -up- GetEvaluationSessionPort 
@enduml