@startuml GetAssetDetail
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    () "GetAssetDetailUseCase" as GetAssetDetailUseCase

    class GetAssetDetailCommand {
        + asset_id: String
        + session_id: String
    }

    !include Domain/AssetEvaluationDetail.puml

    !include ApplicationServices/GetAssetDetailService.puml

    () "GetSessionPort"

    GetAssetDetailService -up- GetAssetDetailUseCase
    GetAssetDetailService .> GetAssetDetailCommand : legge
    GetAssetDetailService --> GetSessionPort : usa
}

package "Outbound Adapter" {
    class InMemoryEvaluationSessionCache <<Session Cache>> {
        - sessions: dictionary[string:EvaluationSession]
        + save_session(session: EvaluationSession): void
        + get_session(session_id: string): EvaluationSession
        + delete_session(session_id: string): void
        + has_active_session(): bool
    }
}

QueryDashboardController --> GetAssetDetailUseCase : usa
InMemoryEvaluationSessionCache -up- GetSessionPort

@enduml