@startuml GetAssetDetail
skinparam linetype ortho
skinparam nodesep 60
skinparam ranksep 60
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    () "GetAssetDetailUseCase" as GetAssetDetailUseCase

    class AssetDetailQuery <<Query DTO>> {
        + session_id: String
        + asset_id: String
    }

    class AssetDetailResponse {
        + asset_id: String
        + name: String
        + type: AssetType
        + description: String
        + stato_aggregato: EvaluationState
        + lista_requisiti: List<RequirementEvalDTO>
    }

    class RequirementEval{
        + codice_requisito: String
        + stato_valutazione: EvaluationState
    }

    !include ApplicationServices/GetAssetDetailService.puml

    !include Domain/EvaluationSession.puml
    !include Domain/EvaluationSheet.puml

    () "GetSessionPort"
    () "EvaluationSessionCachePort"

    GetAssetDetailService -up- GetAssetDetailUseCase
    GetAssetDetailService --( GetSessionPort : richiede
    GetSessionPort --( EvaluationSessionCachePort
    AssetDetail *-- RequirementEval
}

package "Outbound Adapter" {
    class InMemoryEvaluationSessionCache <<Session Cache>> {
        - sessions: dictionary[string:EvaluationSession]
        + save_session(session: EvaluationSession): void
        + get_session(session_id: string): EvaluationSession
        + delete_session(session_id: string): void
        + has_active_session(): bool
    }
}

QueryDashboardController --( GetAssetDetailUseCase : usa
InMemoryEvaluationSessionCache -up- EvaluationSessionCachePort

@enduml