@startuml GetAssetDetail
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    () "GetAssetDetailUseCase" as GetAssetDetailUseCase

    class AssetDetail {
        + asset_id: String
        + name: String
        + type: AssetType
        + description: String
        + aggregate_status: EvaluationState
        + requirement_list: List<RequirementEval>
    }

    class RequirementEval{
        + codice_requisito: String
        + stato_valutazione: EvaluationState
    }

    !include ApplicationServices/GetAssetDetailService.puml

    !include Domain/EvaluationSession.puml
    !include Domain/EvaluationSheet.puml

    () "GetSessionPort"

    GetAssetDetailService -up- GetAssetDetailUseCase
    GetAssetDetailService --> GetSessionPort : usa
    AssetDetail *-- RequirementEval
}

package "Outbound Adapter" {
    class InMemoryEvaluationSessionCache <<Session Cache>> {
        - sessions: dictionary[string:EvaluationSession]
        + save_session(session: EvaluationSession): void
        + get_session(session_id: string): EvaluationSession
        + delete_session(session_id: string): void
        + has_active_session(): bool
    }
}

QueryDashboardController --> GetAssetDetailUseCase : usa
InMemoryEvaluationSessionCache -up- GetSessionPort

@enduml