@startuml GetDeviceDashboard
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    class GetDeviceDashboardQuery <<Query DTO>> {
        + session_id: String
    }

    () "GetDeviceDashboardUseCase"

    !include ApplicationServices/GetDeviceDashboardService.puml

    

    class DashboardDTO <<Response DTO>> {
        + device_id: String
        + device_name: String
        + operating_system: String
        + description: String
        + stato_aggregato: EvaluationState
        + lista_asset: List<AssetSummaryDTO>
    }

    class AssetSummaryDTO <<Response DTO>> {
        + asset_id: String
        + name: String
        + type: AssetType
        + stato_aggregato: EvaluationState
    }

    () "EvaluationSessionCachePort" as EvaluationSessionCachePort

    ' Inclusioni di dominio permesse
    !include Domain/EvaluationSession.puml

    GetDeviceDashboardService -up- GetDeviceDashboardUseCase
    GetDeviceDashboardService -down-( EvaluationSessionCachePort : "richiede"

    GetDeviceDashboardService ..> GetDeviceDashboardQuery : "legge"
    GetDeviceDashboardService ..> DashboardDTO : "popola"
    DashboardDTO *-- AssetSummaryDTO
}

package "Outbound Adapter" {
    class InMemoryEvaluationSessionCache <<Session Cache>> {
        - sessions: dictionary[string:EvaluationSession]
        + save_session(session: EvaluationSession): void
        + get_session(session_id: string): EvaluationSession
        + delete_session(session_id: string): void
        + has_active_session(): bool
    }
}

DashboardQueryController -down-( GetDeviceDashboardUseCase : "usa"
InMemoryEvaluationSessionCache -up- EvaluationSessionCachePort : "implementa"

@enduml