@startuml GetDeviceList
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/FlaskQueryDeviceController.puml
}

package "Application Core" {
    () "GetDeviceListUseCase" as GetDeviceListUseCase
    !include ApplicationServices/GetDeviceListService.puml
    !include Domain/Device.puml
    !include Domain/DeviceSummary.puml
    () "FindAllDevicesPort" as FindAllDevicesPort

    GetDeviceListService .left.> DeviceSummary: popola
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}


GetDeviceListService - GetDeviceListUseCase


GetDeviceListService --> FindAllDevicesPort : usa

FlaskQueryDeviceController --> GetDeviceListUseCase : usa
MongoDeviceAdapter - FindAllDevicesPort

@enduml