@startuml GetDeviceDetail
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/QueryDeviceController.puml
}

package "Application Core" {
    () "GetDeviceDetailUseCase" as GetDeviceDetailUseCase

    class GetDeviceDetailCommand {
        + device_id: String
    }

    !include ApplicationServices/GetDeviceDetailService.puml
    !include Domain/Device.puml
    () "FindDevicePort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}

GetDeviceDetailService - GetDeviceDetailUseCase

GetDeviceDetailService .> GetDeviceDetailCommand : legge

GetDeviceDetailService --> FindDevicePort: usa

QueryDeviceController --> GetDeviceDetailUseCase: usa
MongoDeviceAdapter - FindDevicePort

@enduml