@startuml GetDeviceDashboard
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    () "GetDeviceDashboardUseCase"

    !include ApplicationServices/GetDeviceDashboardService.puml

    class GetDeviceDashboardCommand {
        + device_id: String
    }

    class DashboardCommand {
        + device_id: String
        + device_name: String
        + operating_system: String
        + description: String
        + aggregate_status: EvaluationState
        + asset_list: List<AssetSummaryCommand>
    }

    class AssetSummaryCommand {
        + asset_id: String
        + name: String
        + type: AssetType
        + aggregate_status: EvaluationState
    }

    () "GetEvaluationSessionPort"

   

    GetDeviceDashboardService .right.> GetDeviceDashboardCommand : legge
    GetDeviceDashboardService .down.> DashboardCommand : popola

    DashboardCommand -[hidden]right-------- GetEvaluationSessionPort
    DashboardCommand *-down- AssetSummaryCommand
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

QueryDashboardController -down-> GetDeviceDashboardUseCase : usa
GetDeviceDashboardUseCase -down- GetDeviceDashboardService
GetDeviceDashboardService -down-> GetEvaluationSessionPort : usa
GetEvaluationSessionPort -down- InMemoryEvaluationSessionCache

@enduml