@startuml GetDeviceDashboard
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryDashboardController.puml
}

package "Application Core" {

    () "GetDeviceDashboardUseCase"

    !include ApplicationServices/GetDeviceDashboardService.puml

    class DashboardCommand {
        + device_id: String
        + device_name: String
        + operating_system: String
        + description: String
        + aggregate_status: EvaluationState
        + asset_list: List<AssetSummaryCommand>
    }

    class AssetSummaryCommand {
        + asset_id: String
        + name: String
        + type: AssetType
        + stato_aggregato: EvaluationState
    }

    () "GetSessionPort"

    !include Domain/EvaluationSession.puml

    GetDeviceDashboardService -up- GetDeviceDashboardUseCase
    GetDeviceDashboardService --( GetSessionPort : richiede

    GetDeviceDashboardService ..> GetDeviceDashboardQuery : "legge"
    GetDeviceDashboardService ..> DashboardCommand : popola
    DashboardCommand *-- AssetSummaryCommand
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

QueryDashboardController -down-( GetDeviceDashboardUseCase : usa
InMemoryEvaluationSessionCache -up- GetSessionPort

@enduml