@startuml GetRequirement
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 140
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryEvaluationRequirementsController.puml
}

package "Application Core" {
    () "GetRequirementUseCase"

    !include ApplicationServices/GetRequirementService.puml

    class GetRequirementCommand {
        + session_id: String
        + asset_id: String
        + requirement_id: String
    }

    class RequirementResponse{
        + requirement_code: String
        + requirement_name: String
        + justification: String
        + evaluation_state: EvaluationState
        + dependency_list: List<DependencyResponse>
        + decision_tree: DecisionTreeResponse
    }

    class DecisionTreeResponse{
        + root_node: NodeResponse
    }

    class NodeResponse{
        + node_id: String
        + type: NodeType
        + question_text: String
        + user_answer: Boolean
        + evaluation_state: EvaluationState
    }

    class DependencyResponse{
        + requirement_code: String
        + stato_valutazione: EvaluationState
    }

    () "GetSessionPort"

    ' Allineiamo Response, Command e Porta sotto il Service per far scendere le frecce dritte
    RequirementResponse -[hidden]right-------- GetRequirementCommand
    GetRequirementCommand -[hidden]right-------- GetSessionPort

    ' ==========================================
    ' COLLEGAMENTI INTERNI AL CORE (Top-Down)
    ' ==========================================
    GetRequirementUseCase -down- GetRequirementService
    
    GetRequirementService -down-> GetSessionPort : usa

    GetRequirementService .down.> GetRequirementCommand : legge
    GetRequirementService .down.> RequirementResponse : popola
    
    ' Frecce di composizione rigorosamente verso il basso
    RequirementResponse *-down- DecisionTreeResponse
    RequirementResponse *-down- DependencyResponse
    DecisionTreeResponse *-down- NodeResponse
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

' ==========================================
' COLLEGAMENTI ESTERNI (Inbound -> Core -> Outbound)
' ==========================================
QueryEvaluationRequirementsController -down-> GetRequirementUseCase : usa
GetSessionPort -down- InMemoryEvaluationSessionCache

@enduml