@startuml GetRequirement
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 100
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/QueryEvaluationRequirementsController.puml
}

package "Application Core" {
    () "GetRequirementUseCase"

    class GetRequirementQuery <<Query Command>> {
        + session_id: String
        + asset_id: String
        + requirement_id: String
    }

    !include ApplicationServices/GetRequirementService.puml

    class RequirementResponse{
        + requirement_code: String
        + requirement_name: String
        + justification: String
        + stato_valutazione: EvaluationState
        + dependency_list: List<DependencyResponse>
        + decision_tree: DecisionTreeResponse
    }

    class DecisionTreeResponse{
        + root_node: NodeResponse
    }

    class NodeResponse{
        + node_id: String
        + type: NodeType
        + question_text: String
        + user_answer: Boolean
        + evaluation_state: EvaluationState
    }

    class DependencyResponse{
        + requirement_code: String
        + stato_valutazione: EvaluationState
    }

    () "GetSessionPort"

    !include Domain/EvaluationSession.puml
    !include Domain/EvaluationSheet.puml

    GetRequirementService -up- GetRequirementUseCase
    
    GetRequirementService -down-( GetSessionPort : "richiede sessione"

    GetRequirementService ..> GetRequirementQuery : "legge"
    GetRequirementService ..> RequirementResponse : "popola"
    
    RequirementResponse *-- DecisionTreeResponse
    RequirementResponse *-- DependencyResponse
    DecisionTreeResponse *-- NodeResponse
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

QueryEvaluationRequirementsController -down-( GetRequirementUseCase : "usa"
InMemoryEvaluationSessionCache -up- GetSessionPort

@enduml