@startuml CreateDevice
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteDeviceController.puml
}

package "Application Core" {

    () "ImportDeviceUseCase"

    !include ApplicationServices/ImportDevice<Service.puml

    enum AllowedDeviceFileExtension <<enum>> {
        CSV
        XML
        JSON
    }

    class ImportDeviceCommand <<Command DTO>> {
        + device_file_content: BinaryIO
        + extension: AllowedDeviceFileExtension
    }

    !include ApplicationServices/ImportDeviceService.puml
    !include Domain/Device.puml
    () "FileDeviceImporterPort"
    () "DeviceWriteRepositoryPort"
    () "FileDeviceImporterFactoryPort"
}

package "Outbound Adapter" {
    abstract class FileDeviceImporter <<Template Method>> {
        + parse_device_file(device_file_content: BinaryIO): Device
        # check_metadata(): bool
        # open_stream(): file
        # parse_data()
        # close_stream(): void
    }

    class CSVFileDeviceImporter {
        # check_metadata(): bool
        # open_stream(): file
        # parse_data()
        # close_stream(): void
    }

    class JSONFileDeviceImporter {
        # check_metadata(): bool
        # open_stream(): file
        # parse_data()
        # close_stream(): void
    }

    class XMLFileDeviceImporter {
        # check_metadata(): bool
        # open_stream(): file
        # parse_data()
        # close_stream(): void
    }

    class ConcreteFileDeviceImporterFactory {
        + get_file_device_importer(extension: AllowedDeviceFileExtension): FileDeviceImporterPort
    }
}

ImportDeviceController --( ImportDeviceUseCase : usa

ImportDeviceUseCase - ImportDeviceService

ImportDeviceService ..> FileDeviceImporterPort
ImportDeviceService --( FileDeviceImporterFactoryPort
ImportDeviceService --( DeviceWriteRepositoryPort

FileDeviceImporterFactoryPort - ConcreteFileDeviceImporterFactory
ConcreteFileDeviceImporterFactory .up.> CSVFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> JSONFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> XMLFileDeviceImporter

FileDeviceImporterPort - FileDeviceImporter
FileDeviceImporter <|-down- CSVFileDeviceImporter
FileDeviceImporter <|-down- XMLFileDeviceImporter
FileDeviceImporter <|-down- JSONFileDeviceImporter

@enduml