@startuml import-standard
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 250
skinparam ranksep 120

package "Inbound Adapter" {
    !include InboundAdapters/ImportStandardController.puml
}

package "Application Core" {

    () "ImportStandardUseCase"

    !include ApplicationServices/ImportStandardService.puml

    enum AllowedStandardFileExtension <<enum>> {
        XML
        JSON
    }

    class ImportStandardCommand <<Command DTO>> {
        + standard_file_content: BinaryIO
        + extension: AllowedStandardFileExtension
    }

    () "FileStandardImporterPort"
    () "FileStandardImporterFactoryPort"
    () "StandardSavePort"
}

package "Outbound Adapter" {
    
    !include OutboundAdapters/FileStandardImporter.puml

    class JSONFileStandardImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class XMLFileStandardImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    !include OutboundAdapters/ConcreteFileStandardImporterFactory.puml
    !include OutboundAdapters/MongoStandardAdapter.puml
}

ImportStandardController -right-> ImportStandardUseCase : usa
ImportStandardUseCase -right- ImportStandardService

' Forza spaziatura orizzontale ESTREMA tra le porte aggiungendo trattini
FileStandardImporterPort -[hidden]right-------- FileStandardImporterFactoryPort
FileStandardImporterFactoryPort -[hidden]right-------- StandardSavePort

ImportStandardService -down-> FileStandardImporterPort : usa
ImportStandardService -down-> FileStandardImporterFactoryPort : usa
ImportStandardService -down-> StandardSavePort : usa

' Ripetiamo la spaziatura estrema per gli adapter sottostanti
FileStandardImporter -[hidden]right-------- ConcreteFileStandardImporterFactory
ConcreteFileStandardImporterFactory -[hidden]right-------- MongoStandardAdapter

FileStandardImporterPort -down- FileStandardImporter
FileStandardImporterFactoryPort -down- ConcreteFileStandardImporterFactory
StandardSavePort -down- MongoStandardAdapter

FileStandardImporter <|-down- XMLFileStandardImporter
FileStandardImporter <|-down- JSONFileStandardImporter

ConcreteFileStandardImporterFactory .up.> JSONFileStandardImporter : usa
ConcreteFileStandardImporterFactory .up.> XMLFileStandardImporter : usa

@enduml