@startuml import-device
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100
skinparam packageStyle rectangle
skinparam style strictuml

package "Inbound Adapter" {
    !include InboundAdapters/ImportDeviceController.puml
}

package "Application Core" {

    () "ImportDeviceUseCase"

    !include ApplicationServices/ImportDeviceService.puml

    enum AllowedDeviceFileExtension <<enum>> {
        CSV
        XML
        JSON
    }

    class ImportDeviceCommand {
        + device_file_content: BinaryIO
        + extension: AllowedDeviceFileExtension
    }

    () "FileDeviceImporterPort"
    () "DeviceWriteRepositoryPort"
    () "FileDeviceImporterFactoryPort"
}

package "Outbound Adapter" {
    abstract class FileDeviceImporter <<Template Method>> {
        + parse_device_file(device_file_content: BinaryIO): Device
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class CSVFileDeviceImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class JSONFileDeviceImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class XMLFileDeviceImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class ConcreteFileDeviceImporterFactory {
        + get_file_device_importer(extension: AllowedDeviceFileExtension): FileDeviceImporterPort
    }
}

ImportDeviceController --( ImportDeviceUseCase : usa

ImportDeviceUseCase - ImportDeviceService

ImportDeviceService ..> FileDeviceImporterPort
ImportDeviceService --( FileDeviceImporterFactoryPort
ImportDeviceService --( DeviceWriteRepositoryPort

FileDeviceImporterFactoryPort - ConcreteFileDeviceImporterFactory
ConcreteFileDeviceImporterFactory .up.> CSVFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> JSONFileDeviceImporter
ConcreteFileDeviceImporterFactory .up.> XMLFileDeviceImporter

FileDeviceImporterPort - FileDeviceImporter
FileDeviceImporter <|-down- CSVFileDeviceImporter
FileDeviceImporter <|-down- XMLFileDeviceImporter
FileDeviceImporter <|-down- JSONFileDeviceImporter

@enduml