@startuml import-device
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100

package "Inbound Adapter" {
    !include InboundAdapters/ImportStandardController.puml
}

package "Application Core" {

    () "ImportStandardUseCase"

    !include ApplicationServices/ImportStandardService.puml

    enum AllowedStandardFileExtension <<enum>> {
        XML
        JSON
    }

    class ImportStandardCommand <<Command DTO>> {
        + standard_file_content: BinaryIO
        + extension: AllowedStandardFileExtension
    }

    () "FileStandardImporterPort"
    () "StandardSavePort"
    () "FileStandardImporterFactoryPort"
}

package "Outbound Adapter" {
    
    !include OutboundAdapters/FileStandardImporter.puml

    class JSONFileStandardImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    class XMLFileStandardImporter {
        # check_metadata()
        # open_stream()
        # parse_data()
        # close_stream()
    }

    !include OutboundAdapters/ConcreteFileStandardImporterFactory.puml
    !!include OutboundAdapters/MongoStandardAdapter.puml
}

ImportStandardController --( ImportStandardUseCase : usa

ImportStandardUseCase - ImportStandardService

ImportStandardService ..> FileStandardImporterPort
ImportStandardService --( FileStandardImporterFactoryPort
ImportStandardService --( StandardSavePort

FileStandardImporterFactoryPort - ConcreteFileStandardImporterFactory
ConcreteFileStandardImporterFactory .up.> JSONFileStandardImporter
ConcreteFileStandardImporterFactory .up.> XMLFileStandardImporter

FileStandardImporterPort - FileStandardImporter
FileStandardImporter <|-down- XMLFileStandardImporter
FileStandardImporter <|-down- JSONFileStandardImporter

@enduml