@startuml InsertJustification

skinparam linetype ortho
skinparam nodesep 180 
skinparam ranksep 150
skinparam classAttributeIconSize 0
' Questo parametro è fondamentale per evitare che le scritte tocchino i bordi dei package
skinparam PackagePadding 30 

package "Inbound Adapter" {
    class EvaluationJustificationController <<Flask Blueprint>> {
        +insert_justification(req: Request): Response
    }
}

package "Application Core" {

    () "InsertJustificationUseCase"

    class EvaluationJustificationService <<Application Service>> {
        +insert_justification(command: InsertJustificationCommand): void
    }

    class InsertJustificationCommand {
        +session_id: String
        +asset_id: String
        +requirement_id: String
        +node_id: String
        +justification: String
    }

    () "GetSessionPort"
    () "SaveSessionPort"

    ' ==========================================
    ' GABBIA STRUTTURALE 
    ' ==========================================
    EvaluationJustificationService -[hidden]right-------- InsertJustificationCommand
    GetSessionPort -[hidden]right-------- SaveSessionPort

    ' ==========================================
    ' COLLEGAMENTI INTERNI AL CORE
    ' ==========================================
    EvaluationJustificationService -up- InsertJustificationUseCase
    EvaluationJustificationService .right.> InsertJustificationCommand : legge

    EvaluationJustificationService -down-> GetSessionPort : usa
    EvaluationJustificationService -down-> SaveSessionPort : usa
    
    ' Trucco aggiuntivo per creare spazio sotto le porte e non far tagliare le scritte dal bordo
    hide spacer
    GetSessionPort -[hidden]down- spacer
    SaveSessionPort -[hidden]down- spacer
}

package "Outbound Adapter" {
    class InMemoryEvaluationSessionCache {
        -sessions: dictionary[string:EvaluationSession]
        +create_session(): EvaluationSession
        +delete_session(session_id: String): void
        +get_session(session_id: String): EvaluationSession
        +save_session(session: EvaluationSession): void
        +has_active_session(device_id: String): bool
    }
}

' ==========================================
' COLLEGAMENTI ESTERNI (Inbound -> Core -> Outbound)
' ==========================================
EvaluationJustificationController -down-> InsertJustificationUseCase : usa

InMemoryEvaluationSessionCache -up- GetSessionPort
InMemoryEvaluationSessionCache -up- SaveSessionPort

@enduml