@startuml OpenEvaluationSession

skinparam linetype ortho
skinparam nodesep 150
skinparam ranksep 150
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/EvaluationSessionController.puml
}

package "Application Core" {

    () "OpenEvaluationSessionUseCase"

    !include ApplicationServices/OpenEvaluationSessionService.puml

    class OpenEvaluationSessionCommand {
        + device_id: String
        + session_id: String
    }

    class SessionCoordinator <<Domain Service>> {
        + can_open_session(session_type: SessionType): bool
    }

    () "FindDevicePort"
    () "FindStandardPort"
    () "CreateSessionPort"

   

    OpenEvaluationSessionService -up- OpenEvaluationSessionUseCase
    OpenEvaluationSessionService .down.> OpenEvaluationSessionCommand : legge

    OpenEvaluationSessionService -right-> FindDevicePort : usa
    OpenEvaluationSessionService -down-> FindStandardPort :usa
    OpenEvaluationSessionService -down-> CreateSessionPort :usa

    CreateSessionPort -[hidden]right- OpenEvaluationSessionCommand
    OpenEvaluationSessionCommand -[hidden]right- FindStandardPort
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
    !include OutboundAdapters/MongoStandardAdapter.puml
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

EvaluationSessionController -right-> OpenEvaluationSessionUseCase : usa
MongoDeviceAdapter -up- FindDevicePort
MongoStandardAdapter -up- FindStandardPort
InMemoryEvaluationSessionCache -up- CreateSessionPort

@enduml