@startuml SaveDevice
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteDeviceController.puml
}

package "Application Core" {
    class SaveDeviceCommand <<Command DTO>> {
        + device_name: String
        + device_os: String
        + device_description: String
    }
    () "SaveDeviceUseCase"
    !include ApplicationServices/SaveDeviceService.puml
    !include Domain/Device.puml
    () "SaveDevicePort"

    SaveDeviceUseCase .right.> SaveDeviceCommand
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}


SaveDeviceService - SaveDeviceUseCase


SaveDeviceService ---( SaveDevicePort: usa

WriteDeviceController --( SaveDeviceUseCase: usa
MongoDeviceAdapter - SaveDevicePort

@enduml