@startuml SaveAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    class SaveAssetCommand {
        + asset_id:string
        + name:String
        + type:AssetType
        + description:String
        + session_id: String
    }

    () "SaveAssetUseCase"
    !include ApplicationServices/SaveAssetService.puml
    !include Domain/Asset.puml
    !include Domain/EvaluationSession.puml
    () "SaveSessionPort"
    () "GetSessionPort"

    SaveAssetService .left.> SaveAssetCommand: legge
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


SaveAssetService - SaveAssetUseCase

SaveAssetService --> SaveSessionPort : usa
SaveAssetService --> GetSessionPort : usa

SaveSessionPort -- InMemoryEvaluationSessionCache
GetSessionPort -- InMemoryEvaluationSessionCache

WriteAssetController --> SaveAssetUseCase : usa

@enduml