@startuml SaveEvaluationSession

skinparam linetype ortho
skinparam nodesep 150
skinparam ranksep 150
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    !include InboundAdapters/EvaluationSessionController.puml
}

package "Application Core" {

    () "SaveEvaluationSessionUseCase"

    !include ApplicationServices/SaveEvaluationSessionService.puml

    class SaveEvaluationSessionCommand {
        + session_id: String
    }

    () "SaveEvaluationSessionPort"



    SaveEvaluationSessionService -up- SaveEvaluationSessionUseCase
    SaveEvaluationSessionService .right.> SaveEvaluationSessionCommand : legge
    SaveEvaluationSessionService -down-> SaveEvaluationSessionPort : usa
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}

EvaluationSessionController -down-> SaveEvaluationSessionUseCase : usa
InMemoryEvaluationSessionCache -up- SaveEvaluationSessionPort

@enduml