@startuml UpdateAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    class UpdateAssetCommand {
        + asset_id:string
        + name:String
        + type:AssetType
        + description:String
        + session_id: String
    }

    () "UpdateAssetUseCase"
    !include ApplicationServices/UpdateAssetService.puml
    !include Domain/Asset.puml

    () "SaveSessionPort"
    () "GetSessionPort"

    UpdateAssetService .left.> UpdateAssetCommand: legge
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


UpdateAssetService - UpdateAssetUseCase

UpdateAssetService --> SaveSessionPort : usa
UpdateAssetService --> GetSessionPort : usa

SaveSessionPort -- InMemoryEvaluationSessionCache
GetSessionPort -- InMemoryEvaluationSessionCache

WriteAssetController --> UpdateAssetUseCase : usa

@enduml