@startuml SaveAsset
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteAssetController.puml
}

package "Application Core" {

    class SaveAssetCommand <<Command DTO>> {
        asset_id:string
        name:String
        AssetType:AssetType
        description:String
    }

    () "SaveAssetUseCase"
    !include ApplicationServices/SaveAssetService.puml
    !include Domain/Asset.puml
    () "SaveSessionPort"
    () "GetSessionPort"
    () "EvaluationSessionPort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/InMemoryEvaluationSessionCache.puml
}


SaveAssetService - SaveAssetUseCase

SaveAssetService --( SaveSessionPort : usa
SaveAssetService --( GetSessionPort : usa

SaveSessionPort -- EvaluationSessionPort
GetSessionPort -- EvaluationSessionPort

WriteAssetController --( SaveAssetUseCase : usa
InMemoryEvaluationSessionCache - EvaluationSessionPort

@enduml