@startuml UpdateDevice
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 120
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/FlaskWriteDeviceController.puml
}

package "Application Core" {
    
    !include Domain/Device.puml
    
    class UpdateDeviceCommand  {
        + device_name: String
        + device_os: String
        + device_description: String
    }
    
    !include ApplicationServices/UpdateDeviceService.puml
    
    () "UpdateDeviceUseCase"
    () "SaveDevicePort"

    Device -[hidden]right- UpdateDeviceCommand
    
    UpdateDeviceService .left.> UpdateDeviceCommand: legge

    UpdateDeviceService -right- UpdateDeviceUseCase

    UpdateDeviceService -down-> SaveDevicePort: usa
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}

FlaskWriteDeviceController -down-> UpdateDeviceUseCase: usa

SaveDevicePort -down- MongoDeviceAdapter

@enduml