@startuml UpdateDevice
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 80
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
    !include InboundAdapters/WriteDeviceController.puml
}

package "Application Core" {
    class UpdateDeviceCommand <<Command DTO>> {
        + device_name: String
        + device_os: String
        + device_description: String
    }
    () "UpdateDeviceUseCase"
    !include ApplicationServices/UpdateDeviceService.puml
    !include Domain/Device.puml
    () "SaveDevicePort"
}

package "Outbound Adapter" {
    !include OutboundAdapters/MongoDeviceAdapter.puml
}


UpdateDeviceService - UpdateDeviceUseCase


UpdateDeviceService --( SaveDevicePort: usa

WriteDeviceController --( UpdateDeviceUseCase: usa
MongoDeviceAdapter - SaveDevicePort

@enduml