settings:
      # Percorso dove creare i file (relativo allo script)
      output_dir: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/requisiti/requisiti_obbligatori"

      # Nome del file aggregatore (se lasciato vuoto, non lo crea)
      index_file: "_index.typ"

      # Il prefisso non può contenere il carattere di title separator
      prefix: "RObb"
      # Estensione dei file generati
      extension: ".typ"

      # Regole di numerazione e stile
      formatting:
            padding: 2 # Zeri iniziali: 2 -> "01", 3 -> "001"
            separator: "." # Separatore numeri: "1.1" vs "1-1"
            title_separator: "_" # Separatore tra numero e titolo: "01_Titolo"
            filename_style: "snake_case" # "snake_case" (a_b) o "kebab_case" (a-b)

      # (Opzionale) File template da copiare per i nuovi file
      template_path: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/requisiti/requisiti_obbligatori/config/template.typ"
      index_header_template: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/requisiti/requisiti_obbligatori/config/index_header_template.typ"
      index_row_template: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/requisiti/requisiti_obbligatori/config/index_row_template.typ"
      index_footer_template: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/requisiti/requisiti_obbligatori/config/index_footer_template.typ"
# La struttura gerarchica
structure:
      - prova