@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


class AssetCreateWidget  {
  + submitUrl : String
  + cancelUrl : String
  + redirectUrl : String
  - formModel : useFormModel
  - assetForm : AssetForm
  - asyncButton : AsyncButton
  --
  + AssetCreateWidget(submitUrl : String, cancelUrl : String, redirectUrl : String)
  - createAsset() : Object
  - onSuccess(data : Object) : void
}
AssetCreateWidget ..> assetFormFields : <<use>>

@enduml