@startuml
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 100
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml

class SessionOpenWidget{
        - createSessionUrl:String
        - deviceId:String
        - redirectUrlTemplate:String

        -confirmButton:AsyncButton

        - errorMessage:String
        -openSession():Promise<JSON>
        -onSuccess()
        -onError()

        + SessionOpenWidget(createSessionUrl:String, deviceId:String, redirectUrlTemplate:String)
}


@enduml