@startuml asset-query-service
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 120
skinparam classAttributeIconSize 0

package "Inbound Adapter"{
class FlaskAssetQueryController <<Flask Blueprint>>{
        + __init__(asset_query_use_case:AssetQueryUseCase)
        ' + create_asset(request:Request):Response
        ' + update_asset(request:Request):Response
        ' + delete_asset(asset_id:String):Response 
        + get_asset_by_id(request:Request):Response

} 
  class Request <<Flask>> {
  }

  note right of Request
    Oggetto globale di Flask.
    Accessibile tramite import
    nei metodi dei request handler
    per estrarre i dati della
    richiesta HTTP corrente.
  end note

  FlaskAssetQueryController ..> Request
}

package "Application Core" {

        package "Inbound Port"{


class AssetQueryUseCase{
        + get_asset_by_id(id_device:string, id:string):AssetDetailDTO

}



                ' interface AssetQueryUseCase <<interface>>{
                '                 + get_asset_by_id(id_device:string, id:string):AssetDetailDTO
                ' }

                ' interface AssetWriteUseCase <<interface>>{
                '                 + create_asset(create_data:CreateAssetDTO):bool
                '                 + update_asset(update_data:UpdateAssetDTO):bool
                '                 + delete_asset(id:string):bool
                ' }
                
        }

        package Domain {
                !include Dominio/Device.puml
                !include Dominio/ComplianceStandard.puml
                !include Dominio/EvaluationSheet.puml
        }
        class  AssetQueryService{
                + get_asset_by_id(id_device:string, id:string):AssetDetailDTO
        }

        class AssetDetailDTO{
                + asset_id: string
                + name: string
                + asset_type: AssetType
                + description: string
                + asset_evaluation_state:EvaluationState
                + requirement_evaluations: map<String,EvaluationState>
        }

        package "Outbound Ports"{
                !include ports/out/EvaluationSessionCachePort.puml

        }
}

FlaskAssetQueryController --> AssetQueryUseCase

AssetQueryService -->EvaluationSessionCachePort


AssetQueryService -up-|> AssetQueryUseCase


AssetQueryService ..> AssetDetailDTO 
AssetQueryService ..> EvaluationSheet 
AssetQueryService ..> Device
AssetQueryService ..> ComplianceStandard 



@enduml
