@startuml classe_asset
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 120
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    class AssetController <<Flask Blueprint>> {
        +getListaAsset(device_id: String, req: Request): Response
        +creaAsset(device_id: String, req: Request): Response
        +getDettaglioAsset(device_id: String, asset_id: String): Response
        +modificaAsset(device_id: String, asset_id: String, req: Request): Response
        +eliminaAsset(device_id: String, asset_id: String): Response
    }
}

package "Application Core" {
    
    ' Le interfacce diventano Ball (porte logiche)
    () "InterfaceAssetUseCase" as InboundPort

    class AssetService <<Application Service>> {
        +getListaAsset(device_id: String): List<Asset>
        +creaAsset(device_id: String, dto: CreaAssetDTO): Asset
        +getDettaglioAsset(device_id: String, asset_id: String): Asset
        +modificaAsset(device_id: String, asset_id: String, dto: ModificaAssetDTO): Asset
        +eliminaAsset(device_id: String, asset_id: String): void
        -validaRegoleBusiness(a: Asset): void
    }

    class Asset <<Entity>> {    }

    InboundPort -down- AssetService : "fornisce"
    AssetService -down-( OutboundPort : "richiede"
    AssetService ..> Asset : "crea e modifica"
}

package "Outbound Adapter" {
    class MongoAssetAdapter <<Mongo Repository>> {
        -collection: pymongo.Collection
        +save(device_id: String, a: Asset): void
        +findById(device_id: String, asset_id: String): Asset
        +findAllByDevice(device_id: String): List<Asset>
        +deleteById(device_id: String, asset_id: String): void
    }
}


AssetController -( InboundPort : "utilizza"

OutboundPort -down- MongoAssetAdapter : "implementa"

@enduml