@startuml device
skinparam linetype ortho
skinparam nodesep 120
skinparam ranksep 120
skinparam classAttributeIconSize 0

package "Inbound Adapter" {
    class DeviceController <<Flask Blueprint>> {
        - queryService: QueryDeviceUseCase
        - writeService: WriteDeviceUseCase
        + getListaDispositivi(req: Request): Response
        + createDevice(req: Request): Response
        + getDettaglioDevice(id: String): Response
        + modifyDevice(id: String, req: Request): Response
        + deleteDevice(id: String): Response
    }
}

package "Application Core" {

    () "QueryDeviceUseCase"
    () "DeviceReadRepositoryPort"

    () "DeviceWriteUseCase"
    () "DeviceWriteRepositoryPort"

    class DeviceQueryService <<Application Service>> {
        - repository: DeviceReadRepositoryPort
        + getListaDispositivi(): List<DeviceSummaryDTO>
        + getDettaglioDevice(id: String): Device
    }

    class DeviceWriteService <<Application Service>> {
        - repository: DeviceWriteRepositoryPort
        + createDevice(CreateDeviceDTO): bool
        + modifyDevice(ModifyDeviceDTO): bool 
        + deleteDevice(deviceId: String): bool
    }

    class CreateDeviceDTO {
        + deviceName: String
        + deviceOS: String
        + deviceDescription: String
        + deviceComplianceStandardId: String
    }

    class ModifyDeviceDTO {
        + deviceId: String
        + deviceName: String
        + deviceOS: String
        + deviceDescription: String
    }

    class DeviceSummaryDTO {
        + deviceId: String
        + deviceName: String
    }

    class DeviceDetailDTO {
        + deviceId: String
        + deviceName: String
        + deviceOS: String
        + deviceDescription: String
        + deviceComplianceStandard: String
    }

    QueryDeviceUseCase -down- DeviceQueryService : "fornisce"
    DeviceQueryService -down-( DeviceReadRepositoryPort : "richiede"
    DeviceQueryService ..> Device : "legge"
    DeviceQueryService ..> DeviceSummaryDTO: "popola"
    DeviceQueryService ..> DeviceDetailDTO: "popola"

    DeviceWriteUseCase -- DeviceWriteService : "fornisce"
    DeviceWriteService --( DeviceWriteRepositoryPort: "richiede"

}

package "Outbound Adapter" {
    class MongoDeviceAdapter <<Mongo Repository>> {
        - collection: pymongo.Collection
        + save(d: Device): void
        + findById(id: String): Device
        + findAll(): List<Device>
        + getListDeviceSummary(): List<DeviceSummary>
        + deleteById(id: String): void
    }
}

DeviceController -( QueryDeviceUseCase : "utilizza"
DeviceController -( DeviceWriteUseCase: "utilizza"


DeviceReadRepositoryPort -- MongoDeviceAdapter : "implementa"
DeviceWriteRepositoryPort -- MongoDeviceAdapter: "implementa"

@enduml