@startuml

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 80
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


package "Inbound Adapter"{

        class EvaluationDecisionNodeController <<Flask Blueprint>>{
                + insert_answer(Request):Response

        }

}
package "Application Core"{

        package "Inbound Port"{
                interface EvaluationDecisionNodeUseCase {
                        + insert_answer(answer:bool, device_id:string, asset_id: String, requirement_id:String, node_id:String)
                }
        }

                class EvaluationDecisionNodeService {
                        + insert_answer(answer:bool, device_id:string, asset_id: String, requirement_id:String, node_id:String)
                }


        package "Outbound Port"{
                class EvaluationSessionCachePort{

                }
        }





}



EvaluationDecisionNodeController --> EvaluationDecisionNodeUseCase
EvaluationDecisionNodeUseCase ..|> EvaluationDecisionNodeService

EvaluationDecisionNodeService --> EvaluationSessionCachePort

@enduml