@startuml

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 80
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


package "Inbound Adapter"{
class EvaluationRequirementsQueryController <<Flask Blueprint>>{
        + __init__(requirement_query_use_case:EvaluationRequirementsQueryUseCase)
        + get_requirement_view_by_id(request:Request):Response

} 

}


package "Application Core" {

        package "Inbound Port"{

               class EvaluationRequirementsQueryUseCase{
                        + get_requirement_view_by_id(device_id,asset_id,requirement_id):RequirementViewDTO

               }
                
        }

                
        package Domain {
                class EvaluationSheet{}

                class EvaluationSession{}

        }


        package "Outbound Ports"{
        }
}



@enduml