@startuml justification

skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 80
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
skinparam style strictuml


package "Inbound Adapter"{

        class EvaluationJustificationController <<Flask Blueprint>>{
                + insert_justification(Request):Response

        }

}
package "Application Core"{

        package "Inbound Port"{
                interface EvaluationJustificationUseCase {
                        + insert_justification(justification:string, device_id:string, asset_id: String, requirement_id:String, node_id:String)
                }
        }

                class EvaluationJustificationService {
                        + insert_justification(justificatio:String, device_id:string, asset_id: String, requirement_id:String, node_id:String)
                }


        package "Outbound Port"{
                class EvaluationSessionCachePort{

                }
        }





}



EvaluationJustificationController --> EvaluationJustificationUseCase
EvaluationJustificationUseCase ..|> EvaluationJustificationService

EvaluationJustificationService --> EvaluationSessionCachePort

@enduml