@startuml EvaluationSession
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 80
skinparam ranksep 100
skinparam packageStyle rectangle
skinparam style strictuml



package "Inbound Adapter" {
  class FlaskSessionRequestHandler <<Flask Blueprint>> {
    ' - session_port: EvaluationSessionUseCase
    + __init__(session_port: EvaluationSessionUseCase)
    + open_session(): Response
    + save_session(session_id:String): Response
    + save_and_close(session_id:String): Response
    + close_session(session_id:String): Response
  }



  ' class Request <<Flask>> {
  ' }

  ' note right of Request
  '   Oggetto globale di Flask.
  '   Accessibile tramite import
  '   nei metodi dei request handler
  '   per estrarre i dati della
  '   richiesta HTTP corrente.
  ' end note
}








package "Business Logic" {

  package "Logica di Dominio" {

!include Dominio/SessionHandler.puml
!include Dominio/EvaluationSession.puml


  }

  package "Logica Applicativa" {
    class EvaluationSessionService  {

      - session_cache: EvaluationSessionCachePort
      - device_writer: DeviceWriterPort
      + __init__(session_cache: EvaluationSessionCachePort, device_reader:DeviceReadRepositoryPort, device_writer: DeviceWritePort,standard_reader:StandardRepositoryPort)
      + open_session(device_id: string, model_id: string): string
      + commit(): void
      + rollback(): void
    }


  class SessionCoordinator{
    + can_open_session(session_type:SessionType)
  }

  }


  package "Inbound Ports" {
    interface EvaluationSessionUseCase <<interface>> {
      + open_session(device_id: string, model_id: string): string
      + save(session_id): void
      + close(session_id): void
    }



  }

  package "Outbound Ports" {
    interface EvaluationSessionCachePort <<interface>> {
      + save_session(session: Session): void
      + get_session(session_id: string): Session
      + delete_session(session_id: string): void
      + has_active_session(): bool
    }


    interface DeviceWritePort <<interface>> {
      + save_device(device: Device): void
    }
    interface StandardRepositoryPort <<interface>> {
      + get_compliance_standard(standard_id:String ): void
    }
    interface DeviceReadPort <<interface>> {
      + get_device(device_id: String): void
    }

  }
}



package "Outbound Adapter" {
  class InMemorySessionCache {
    - sessions: dictionary[string:Session]
    + save_session(session: Session): void
    + get_session(session_id: string): Session
    + delete_session(session_id: string): void
    + has_active_session(): bool
  }
}

' --- Relazioni ---

FlaskSessionRequestHandler --> EvaluationSessionUseCase
EvaluationSessionUseCase <|-- EvaluationSessionService
EvaluationSessionService --> EvaluationSessionCachePort
EvaluationSessionService --> DeviceWritePort
EvaluationSessionService --> StandardRepositoryPort
EvaluationSessionService --> DeviceReadPort
EvaluationSessionService --> SessionCoordinator

SessionCoordinator --> EditingSessionCachePort 
SessionCoordinator --> EvaluationSessionCachePort 
SessionCoordinator ..> SessionHandler

@enduml