settings:
      # Percorso dove creare i file (relativo allo script)
      output_dir: "src/RTB/DocumentazioneEsterna/Analisi_dei_Requisiti/content/use_case"

      # Nome del file aggregatore (se lasciato vuoto, non lo crea)
      index_file: "_index.typ"

      # Il prefisso non può contenere il carattere di title separator
      prefix: "UC"
      # Estensione dei file generati
      extension: ".typ"

      # Regole di numerazione e stile
      formatting:
            padding: 2 # Zeri iniziali: 2 -> "01", 3 -> "001"
            separator: "." # Separatore numeri: "1.1" vs "1-1"
            title_separator: "_" # Separatore tra numero e titolo: "01_Titolo"
            filename_style: "snake_case" # "snake_case" (a_b) o "kebab_case" (a-b)

      # (Opzionale) File template da copiare per i nuovi file
      template_path: "scripts/use_case_generator/template.typ"

# La struttura gerarchica
structure:
      - Autenticazione:
              - Inserimento username
              - Inserimento password
      - Errore autenticazione
      - Inserimento di un nuovo dispositivo:
      - Creazione di un nuovo dispositivo per la verifica:
            - Inserimento dati dispositivo: 
                  - Inserimento nome dispositivo
                  - Inserimento sistema operativo dispositivo
                  - Inserimento versione firmware dispositivo
                  - Inserimento funzionalita dispositivo
                  - Inserimento descrizione dispositivo
      - Caricamento di un dispositivo per la verifica:
            - Selezione file sorgente:
                  - Selezione file JSON
                  - Selezione file XML
                  - Selezione file CSV
      - Errore importazione file :  
      - Visualizza dati del dispostivo: 
            - Visualizza nome dispositivo
            - Visualizza sistema operativo dispositivo
            - Visualizza versione firmware dispositivo
            - Visualizza funzionalita dispositivo
            - Visualizza descrizione dispositivo

      - Modifica di un dispositivo:

      - Chiusura sessione di verifica attuale:
            - Errore durante il salvataggio automatico

      # - Seleziona file:
      #       - Selezione di un file tramite finestra
      #       - Selezione con drag and drop:
      #             - Drag and drop fuori dalla drop zone
      # - Annulla selezione
      # - Errore nella selezione
      - Importa lista di file di asset
      - Importa file asset singolo:
      - Errore importazione file asset:
            - Importazione di asset appartenenti a uno standard diverso
            - Errore struttura di alcuni asset non valida
      - Visualizza riepilogo di importazione
      - Errore conflitto merge asset
      - Risoluzione conflitto di merge
      - Visualizza lista asset:
            - Visualizza asset singolo
            - Visualizza riepilogo requisiti:
                  - Vedi numero PASS
                  - Vedi numero FAIL
                  - Vedi numero NOT APPLICABLE
      - Visualizza riepilogo risultati:
            - Vedi numero di asset in sospeso
      - Aggiunta asset tramite interfaccia
      - Eliminazione di un asset
      - Modifica asset
      - Cerca asset
      - Salva modifica asset
      - Inserimento dati non validi:
      - Esporta lista asset:
            - Esporta lista asset .xml
            - Esporta lista asset .json
            - Esporta lista asset .csv
            - Esporta lista asset .pdf
      - Errore nell'esportazione
      - Errore nel salvataggio dei dati degli asset
      - Visualizza decision tree
      - Esegui decision tree
      - Aggiungi giustificazione al nodo
      - Visualizza risultato dell'esecuzione
      - Modifica percorso dell'esecuzione
      - Navigazione del decision tree
      - Esporta risultato dell'esecuzione
      - Visualizza nodo decision tree:
            - Visualizza primo nodo
            - Visualizza nodo intermedio
            - Visualizza foglia
      - Modifica della struttura del decision tree:
            - Modifica con editor grafico:
                  - Modifica testo di una domanda
                  - Modifica connessione tra i nodi
                  - Aggiungi nodo: 
                        - Aggiungi nodo di decisione 
                        - Aggiungi nodo foglia
                  - Rimozione nodo 
            - Importazione nuova struttura 
      - Struttura non valida dopo la modifica
      - Salvataggio modifiche alla struttura dei DT
      - Errore nel salvataggio della struttura del decision tree
      - Visualizza cronologia dei dispositivi verificati
      - Elimina dispositivo:
      - Annullamento creazione dispositivo:
      # - Importa file test di conformità
      # - Errore nell'importaizone dei test
      # - Visualizza lista test di conformità:
      #       - Visualizza test di conformità
      # - Lista dei test vuota
      # - Aggiungi test di conformità
      # - Errore nell'aggiunta
      # - Elimina test di conformità
      # - Errore nell'eliminazione
      # - Modifica test di conformità
      # - Errore nella modifica


