@startuml Modello_di_Dominio
skinparam linetype ortho
skinparam packageStyle rectangle

package "1. Evaluation Object" {
    !include Device.puml
    !include AssetAnagraphic.puml
    !include AssetType.puml
    !include Asset.puml
    !include AssetProprieties.puml
    !include AssetEvidence.puml
}

package "2. Compliance Standard" {
    !include ComplianceStandard.puml
    !include DecisionNode.puml
    !include Node.puml
    !include LeafNode.puml
    !include DecisionTree.puml
    !include Requirement.puml
}

package "3. Evaluation Engine" {
    !include EvaluationEngine.puml
    !include EvaluationState.puml
    !include Verdict.puml


}

package "4. Evaluation Output" {
    !include DeviceEvaluationResult.puml
    !include AssetEvaluationResult.puml
    !include RequirementEvaluationResult.puml

    !include DeviceEvaluationResultWithAnagraphic.puml
    !include AssetEvaluationResultWithAnagraphic.puml
    !include RequirementEvaluationResultWithAnagraphic.puml
}

package "5. Session" {
    !include SessionType.puml
    !include SessionHandler.puml
}


EvaluationEngine --> DeviceEvaluationResult


@enduml