@startuml Asset
skinparam classAttributeIconSize 0
class Asset {
    - asset_id: String
    - asset_anagraphic: AssetAnagraphic
    - asset_proprieties: AssetProprieties
    + set_node_choice(requirement_id: String, node_id: String, value: Bool): void
    + set_justification(requirement_id: String, node_id: String, value: Bool): void
    + update_anagraphic(name: string, type: AssetType, description: String): void
}

Asset *-- "1..1" AssetAnagraphic
Asset *-- "1..1" AssetProprieties

@enduml