@startuml AssetProprieties

class AssetProprieties {
    - evidences: Map<String, AssetEvidence>

    + evidences(): Map<String, AssetEvidence> <<property>>
    + get_evidence(requirement_id: String): AssetEvidence
    + set_node_choice(requirement_id: String, node_id: String, value: Bool): void
    + set_justification(requirement_id: String, justification: String): void
}

AssetProprieties *-- "1..*" AssetEvidence

@enduml