@startuml EvaluationEngine

class EvaluationEngine {
 
    + evaluate(device: Device, standard: ComplianceStandard): DeviceEvaluationResult
    - _evaluate_asset(asset: Asset, standard: ComplianceStandard): AssetEvaluationResult
    - _resolve(requirement_id: str, standard: ComplianceStandard, asset: Asset, cache: dict[str, RequirementResult]): RequirementResult
    - _aggregate_evaluation_states(states: Sequence<EvaluationState>): EvaluationState
}

@enduml