@startuml EvaluationSession
skinparam linetype ortho
skinparam classAttributeIconSize 0

class EvaluationSession {
    ' - evaluationSheet: EvaluationSheet
    - session_id: String
}
EvaluationSession --> Device
EvaluationSession --> ComplianceStandard
@enduml