@startuml Requirement
skinparam linetype ortho
skinparam classAttributeIconSize 0

class Requirement {
    - code: String
    - name: String
    - description: String
    - target: String
}
Requirement *-- "1" DecisionTree

@enduml