@startuml RequirementEvaluationDetail

class RequirementEvaluationDetail {
    - requirement_id: String
    - name: String
    - description: String
    - target: String
    - justification: String
    - node_coiches: MappingProxyType
    - state: EvaluationState
    - dependencies: tuple[tuple[str, EvaluationState], ...]
}

@enduml