@startuml Importazione_dispositivo_uc05_06

actor "Utente" as utente
participant "<<Boundary>>\nVue.js" as vue
participant "<<Inbound Adapter>>\nImportDeviceController" as controller
participant "<<Utility>>\nHttpRequestHelper" as helper
participant "<<Service>>\nImportDeviceService" as service
participant "<<Outbound Adapter>>\nConcreteFileImporterFactory" as factory
participant "<<Outbound Adapter>>\nFileDeviceImporter (es. CSV)" as parser
participant "<<Domain>>\nDeviceBuilder" as builder
participant "<<Outbound Adapter>>\nMongoDeviceAdapter" as repo

utente -> vue: Carica file (CSV/XML/JSON)
activate vue

vue -> controller: POST /api/devices/import
activate controller

controller -> helper: estrai_payload_e_estensione()
activate helper
helper --> controller: file_content, ext
deactivate helper

controller -> service: import_device(file_content, ext)
activate service

service -> factory: get_file_device_importer(ext)
activate factory
factory --> service: parser_corretto
deactivate factory

service -> parser: parse_device_file(file_content)
activate parser
alt UC06 - Errore formato file (es. CSV corrotto)
    parser --> service: ParseException
    service --> controller: Errore di parsing
    controller --> vue: HTTP 400 Bad Request
    vue --> utente: Errore: formato del file non valido
else Sintassi Corretta
    parser --> service: DeviceFileDTO (Dati estratti)
end
deactivate parser

service -> builder: device_DTO_to_device(DeviceFileDTO)
activate builder
builder -> builder: valida_regole_business()

alt UC06 - Errore semantica (es. Mac Address invalido)
    builder --> service: Device nullo, ErrorLog (popolato)
    service --> controller: ErrorLog
    controller --> vue: HTTP 422 Unprocessable Entity (con ErrorLog)
    vue --> utente: Mostra lista di tutti gli errori nel file
else L'entità rispetta le regole
    builder --> service: nuovo_dispositivo, ErrorLog (vuoto)
end
deactivate builder

service -> repo: save(nuovo_dispositivo)
activate repo
repo --> service: success
deactivate repo

service --> controller: success (ErrorLog vuoto)
deactivate service

controller --> vue: HTTP 201 Created
deactivate controller

vue --> utente: Dispositivo importato con successo
deactivate vue

@enduml