@startuml ConcreteFileDeviceExporterFactory

class ConcreteFileDeviceExporterFactory <<Factory Adapter>> {
    + get_file_device_exporter(extension: AllowedDeviceFileExtension): FileDeviceExporterPort
}

@enduml