@startuml InMemoryEvaluationSessionCache
skinparam classAttributeIconSize 0
class InMemoryEvaluationSessionCache {
    - sessions: dictionary[string:EvaluationSession]
    + create_session(): EvaluationSession
    + delete_session(session_id: String): void
    + get_session(session_id: String): EvaluationSession
    + save_session(session: EvaluationSession): void
    + has_active_session(device_id: String): bool
}

@enduml