@startuml InMemoryEvaluationSessionCache

class InMemoryEvaluationSessionCache {
    - sessions: dictionary[string:EvaluationSession]
    + create_session(): SessionReturn
    + delete_session(session: CloseSessionCommand): void
    + get_session(session: EvaluationSession): EvaluationSession
    + save_session(session: EvaluationSession): void
    + has_active_session(): bool
}

@enduml