@startuml MongoStandardAdapter
skinparam classAttributeIconSize 0
class MongoStandardAdapter <<Mongo Repository>> {
    + save(standard: ComplianceStandard): void
    + find_by_id(standard_id: String): ComplianceStandard
}

@enduml